Config = {}

Config.Prompts = {
    Prompt1 = 0x05CA7C52,
    Sell = 0x05CA7C52,
    Shop = 0x43DBF61F,
}

Config.InventoryConvertItemJob = {"hunter"}

Config.Textures = {
    cross = {"scoretimer_textures", "scoretimer_generic_cross"},
    locked = {"menu_textures","stamp_locked_rank"},
    tick = {"scoretimer_textures","scoretimer_generic_tick"},
    money = {"inventory_items", "money_moneystack"},
    alert = {"menu_textures", "menu_icon_alert"},
}

Config.Texts = {
    Prompt1 = "Put Away",
    Sell = "Sell",
    Shop = "Trade Pelts",
    Pelt = "Pelt",
    NoEntry = "No entry found for pelt!",
    SellDesc = "Select to Sell",
    Products = "Products",
    PeltTrader = "Pelt Trader",
    NoItems = "You dont have any pelt to sell!",
    StoredPelt = "You have stored some pelt!",
    CantStore = "You cant store it now!",
    Sold = "You have sold:",
    NoJob = "You dont have the required job!",
    For = "for",
    SoldPelt = "You have sold the pelt!",
    --Update 2023. 08. 09
    CantStore2 = "Cant store this pelt!",
}

Config.PeltTraders = {
    [1] = {
        name = "Pelt Trader",
        blip = {enable = true, sprite = 249721687},
        coords = vector3(-2345.162, -2374.237, 62.306),
        job = false,--job = false for no job
        multiplier = 0.8, -- basic pelt price * multiplier
    },
    [2] = {
        name = "Pelt Trader",
        blip = {enable = true, sprite = 249721687},
        coords = vector3(-3695.49, -2623.25, -13.79),
        job = false,--job = false for no job
        multiplier = 0.3, -- basic pelt price * multiplier
    },
    [3] = {
        name = "Pelt Trader",
        blip = {enable = true, sprite = 249721687},
        coords = vector3(-5511.67, -2951.07, -1.84),
        job = false,--job = false for no job
        multiplier = 0.3, -- basic pelt price * multiplier
    },
    [4] = {
        name = "Pelt Trader",
        blip = {enable = true, sprite = 249721687},
        coords = vector3(-751.89, -1277.91, 43.41),
        job = false,--job = false for no job
        multiplier = 0.3, -- basic pelt price * multiplier
    },
    [5] = {
        name = "Pelt Trader",
        blip = {enable = true, sprite = 249721687},
        coords = vector3(-1756.27, -395.5, 156.11),
        job = false,--job = false for no job
        multiplier = 0.3, -- basic pelt price * multiplier
    },
    [6] = {
        name = "Pelt Trader",
        blip = {enable = true, sprite = 249721687},
        coords = vector3(-335.3, 762.14, 116.58),
        job = false,--job = false for no job
        multiplier = 0.3, -- basic pelt price * multiplier
    },
    [7] = {
        name = "Pelt Trader",
        blip = {enable = true, sprite = 249721687},
        coords = vector3(-335.3, 762.14, 116.58),
        job = false,--job = false for no job
        multiplier = 0.3, -- basic pelt price * multiplier
    },
    [8] = {
        name = "Pelt Trader",
        blip = {enable = true, sprite = 249721687},
        coords = vector3(1300.63, -1274.25, 75.96),
        job = false,--job = false for no job
        multiplier = 0.3, -- basic pelt price * multiplier
    },
    [9] = {
        name = "Pelt Trader",
        blip = {enable = true, sprite = 249721687},
        coords = vector3(2936.28, 1301.33, 44.48),
        job = false,--job = false for no job
        multiplier = 0.3, -- basic pelt price * multiplier
    },
    [10] = {
        name = "Pelt Trader",
        blip = {enable = true, sprite = 249721687},
        coords = vector3(-1326.7781, 2474.3555, 309.7417),
        job = false,--job = false for no job
        multiplier = 0.3, -- basic pelt price * multiplier
    },
    [11] = {
        name = "Pelt Trader",
        blip = {enable = true, sprite = 249721687},
        coords = vector3(463.2, 2234.76, 247.55),
        job = false,--job = false for no job
        multiplier = 0.3, -- basic pelt price * multiplier
    },
    [12] = {
        name = "Pelt Trader",
        blip = {enable = true, sprite = 249721687},
        coords = vector3(2974.6855, 580.6785, 44.4367),
        job = false,--job = false for no job
        multiplier = 0.3, -- basic pelt price * multiplier
    },
}

Config.Pelts = {
    --[id] = {label, itemname, disable_store (true/false)}
    [`PROVISION_BEAR_FUR_POOR`] = {"Bear Fur (Poor)", "bear_pelt_poor", true}, -- DISABLE INVENTORY STORE EXAMPLE: 3rd param is true, so it cannot be stored in inventory
    [`PROVISION_BEAR_FUR_PRISTINE`] = {"Bear Fur (Pristine)", "bear_pelt_pristine"},
    [`PROVISION_BEAR_FUR`] = {"Bear Fur (Good)", "bear_pelt_good"},
    [`PROVISION_BEAR_LEGENDARY_FUR_PRISTINE`] = {"Legendary Bear Fur", "legendary_bear_pelt"},
    [`PROVISION_BEAVER_FUR_POOR`] = {"Beaver Fur (Poor)", "beaver_pelt_poor"},
    [`PROVISION_BEAVER_FUR_PRISTINE`] = {"Beaver Fur (Pristine)", "beaver_pelt_pristine"},
    [`PROVISION_BEAVER_FUR`] = {"Beaver Fur (Good)", "beaver_pelt_good"},
    [`PROVISION_BEAVER_LEGENDARY_FUR_PRISTINE`] = {"Legendary Beaver Fur", "legendary_beaver_pelt"},
    [`PROVISION_BLACK_BEAR_FUR_POOR`] = {"Black Bear Fur (Poor)", "black_bear_pelt_poor"},
    [`PROVISION_BLACK_BEAR_FUR_PRISTINE`] = {"Black Bear Fur (Pristine)", "black_bear_pelt_pristine"},
    [`PROVISION_BLACK_BEAR_FUR`] = {"Black Bear Fur (Good)", "black_bear_pelt_good"},
    [`PROVISION_BOAR_LEGENDARY_SKIN_PRISTINE`] = {"Legendary Boar Skin", "legendary_boar_pelt"},
    [`PROVISION_BOAR_SKIN_POOR`] = {"Boar Skin (Poor)", "boar_pelt_poor"},
    [`PROVISION_BOAR_SKIN_PRISTINE`] = {"Boar Skin (Pristine)", "boar_pelt_pristine"},
    [`PROVISION_BOAR_SKIN`] = {"Boar Skin (Good)", "boar_pelt_good"},
    [`PROVISION_BUCK_FUR_POOR`] = {"Buck Fur (Poor)", "buck_pelt_poor"},
    [`PROVISION_BUCK_FUR_PRISTINE`] = {"Buck Fur (Pristine)", "buck_pelt_pristine"},
    [`PROVISION_BUCK_FUR`] = {"Buck Fur (Good)", "buck_pelt_good"},
    [`PROVISION_BUCK_LEGENDARY_FUR_PRISTINE`] = {"Legendary Buck Fur", "legendary_buck_pelt"},
    [`PROVISION_BUFFALO_FUR_POOR`] = {"Buffalo Fur (Poor)", "buffalo_pelt_poor"},
    [`PROVISION_BUFFALO_FUR_PRISTINE`] = {"Buffalo Fur (Pristine)", "buffalo_pelt_pristine"},
    [`PROVISION_BUFFALO_FUR`] = {"Buffalo Fur (Good)", "buffalo_pelt_good"},
    [`PROVISION_BULL_HIDE_POOR`] = {"Bull Hide (Poor)", "bull_pelt_poor"},
    [`PROVISION_BULL_HIDE_PRISTINE`] = {"Bull Hide (Pristine)", "bull_pelt_pristine"},
    [`PROVISION_BULL_HIDE`] = {"Bull Hide (Good)", "bull_pelt_good"},
    [`PROVISION_COUGAR_FUR_POOR`] = {"Cougar Fur (Poor)", "cougar_pelt_poor"},
    [`PROVISION_COUGAR_FUR_PRISTINE`] = {"Cougar Fur (Pristine)", "cougar_pelt_pristine"},
    [`PROVISION_COUGAR_FUR`] = {"Cougar Fur (Good)", "cougar_pelt_good"},
    [`PROVISION_COUGAR_LEGENDARY_FUR_PRISTINE`] = {"Legendary Cougar Fur", "legendary_cougar_pelt"},
    [`PROVISION_COW_HIDE_POOR`] = {"Cow Hide (Poor)", "cow_pelt_poor"},
    [`PROVISION_COW_HIDE_PRISTINE`] = {"Cow Hide (Pristine)", "cow_pelt_pristine"},
    [`PROVISION_COW_HIDE`] = {"Cow Hide (Good)", "cow_pelt_good"},
    [`PROVISION_COYOTE_FUR_POOR`] = {"Coyote Fur (Poor)", "coyote_pelt_poor"},
    [`PROVISION_COYOTE_FUR_PRISTINE`] = {"Coyote Fur (Pristine)", "coyote_pelt_pristine"},
    [`PROVISION_COYOTE_FUR`] = {"Coyote Fur (Good)", "coyote_pelt_good"},
    [`PROVISION_COYOTE_LEGENDARY_FUR_PRISTINE`] = {"Legendary Coyote Fur", "legendary_coyote_pelt"},
    [`PROVISION_DEER_HIDE_POOR`] = {"Hide (Poor)", "base_pelt_poor"},
    [`PROVISION_DEER_HIDE_PRISTINE`] = {"Hide (Pristine)", "base_pelt_pristine"},
    [`PROVISION_DEER_HIDE`] = {"Hide (Good)", "base_pelt_good"},
    [`PROVISION_ELK_FUR_POOR`] = {"Elk Fur (Poor)", "elk_pelt_poor"},
    [`PROVISION_ELK_FUR_PRISTINE`] = {"Elk Fur (Pristine)", "elk_pelt_pristine"},
    [`PROVISION_ELK_FUR`] = {"Elk Fur (Good)", "elk_pelt_good"},
    [`PROVISION_ELK_LEGENDARY_FUR_PRISTINE`] = {"Legendary Elk Fur", "legendary_elk_pelt"},
    [`PROVISION_FOX_FUR_POOR`] = {"Fox Fur (Poor)", "fox_pelt_poor"},
    [`PROVISION_FOX_FUR_PRISTINE`] = {"Fox Fur (Pristine)", "fox_pelt_pristine"},
    [`PROVISION_FOX_FUR`] = {"Fox Fur (Good)", "fox_pelt_good"},
    [`PROVISION_FOX_LEGENDARY_FUR_PRISTINE`] = {"Legendary Fox Fur", "legendary_fox_pelt"},
    [`PROVISION_GOAT_HAIR_POOR`] = {"Goat Hair (Poor)", "goat_pelt_poor"},
    [`PROVISION_GOAT_HAIR_PRISTINE`] = {"Goat Hair (Pristine)", "goat_pelt_pristine"},
    [`PROVISION_GOAT_HAIR`] = {"Goat Hair (Good)", "goat_pelt_good"},
    [`PROVISION_JAVELINA_SKIN_POOR`] = {"Javelina Skin (Poor)", "javelina_pelt_poor"},
    [`PROVISION_JAVELINA_SKIN_PRISTINE`] = {"Javelina Skin (Pristine)", "javelina_pelt_pristine"},
    [`PROVISION_JAVELINA_SKIN`] = {"Javelina Skin (Good)", "javelina_pelt_good"},
    [`PROVISION_MOOSE_FUR_POOR`] = {"Moose Fur (Poor)", "moose_pelt_poor"},
    [`PROVISION_MOOSE_FUR_PRISTINE`] = {"Moose Fur (Pristine)", "moose_pelt_pristine"},
    [`PROVISION_MOOSE_FUR`] = {"Moose Fur (Good)", "moose_pelt_good"},
    [`PROVISION_MOOSE_LEGENDARY_FUR_PRISTINE`] = {"Legendary Moose Fur", "legendary_moose_pelt"},
    [`PROVISION_OXEN_HIDE_POOR`] = {"Oxen Hide (Poor)", "ox_pelt_poor"},
    [`PROVISION_OXEN_HIDE_PRISTINE`] = {"Oxen Hide (Pristine)", "ox_pelt_pristine"},
    [`PROVISION_OXEN_HIDE`] = {"Oxen Hide (Good)", "ox_pelt_good"},
    [`PROVISION_PANTHER_FUR_POOR`] = {"Panther Fur (Poor)", "panther_pelt_poor"},
    [`PROVISION_PANTHER_FUR_PRISTINE`] = {"Panther Fur (Pristine)", "panther_pelt_pristine"},
    [`PROVISION_PANTHER_FUR`] = {"Panther Fur (Good)", "panther_pelt_good"},
    [`PROVISION_PANTHER_LEGENDARY_FUR_PRISTINE`] = {"Legendary Panther Fur", "legendary_panther_pelt"},
    [`PROVISION_PIG_SKIN_POOR`] = {"Pig Skin (Poor)", "pig_pelt_poor"},
    [`PROVISION_PIG_SKIN_PRISTINE`] = {"Pig Skin (Pristine)", "pig_pelt_pristine"},
    [`PROVISION_PIG_SKIN`] = {"Pig Skin (Good)", "pig_pelt_good"},
    [`PROVISION_PRONGHORN_FUR_POOR`] = {"Pronghorn Fur (Poor)", "pronghorn_pelt_poor"},
    [`PROVISION_PRONGHORN_FUR_PRISTINE`] = {"Pronghorn Fur (Pristine)", "pronghorn_pelt_pristine"},
    [`PROVISION_PRONGHORN_FUR`] = {"Pronghorn Fur (Good)", "pronghorn_pelt_good"},
    [`PROVISION_PRONGHORN_LEGENDARY_FUR_PRISTINE`] = {"Legendary Pronghorn Fur", "legendary_pronghorn_pelt"},
    [`PROVISION_RAM_HIDE_POOR`] = {"Ram Hide (Poor)", "ram_pelt_poor"},
    [`PROVISION_RAM_HIDE_PRISTINE`] = {"Ram Hide (Pristine)", "ram_pelt_pristine"},
    [`PROVISION_RAM_HIDE`] = {"Ram Hide (Good)", "ram_pelt_good"},
    [`PROVISION_RAM_LEGENDARY_HIDE_PRISTINE`] = {"Legendary Ram Hide", "legendary_ram_pelt"},
    [`PROVISION_SHEEP_WOOL_POOR`] = {"Sheep Wool (Poor)", "sheep_pelt_poor"},
    [`PROVISION_SHEEP_WOOL_PRISTINE`] = {"Sheep Wool (Pristine)", "sheep_pelt_pristine"},
    [`PROVISION_SHEEP_WOOL`] = {"Sheep Wool (Good)", "sheep_pelt_good"},
    [`PROVISION_TAKANTA_BUFFALO_LEGENDARY_FUR_PRISTINE`] = {"Takanta Buffalo Fur", "takanta_bison_pelt"},
    [`PROVISION_WHITE_BUFFALO_LEGENDARY_FUR_PRISTINE`] = {"Whtie Buffalo Fur", "white_bison_pelt"},
    [`PROVISION_WOLF_FUR_POOR`] = {"Wolf Fur (Poor)", "wolf_pelt_poor"},
    [`PROVISION_WOLF_FUR_PRISTINE`] = {"Wolf Fur (Pristine)", "wolf_pelt_pristine"},
    [`PROVISION_WOLF_FUR`] = {"Wolf Fur (Good)", "wolf_pelt_good"},
    [`PROVISION_WOLF_LEGENDARY_FUR_PRISTINE`] = {"Legendary Wolf Fur", "legendary_wolf_pelt"},
    [`provision_alligator_skin_pristine`] = {"Small Alligator Skin (Pristine)", "alligator_s_pelt_pristine"},
    [`provision_alligator_skin_poor`] = {"Small Alligator Skin (Poor)", "alligator_s_pelt_poor"},
    [`provision_alligator_skin`] = {"Small Alligator Skin (Good)", "alligator_s_pelt_good"},
    [-1243878166] = {"Alligator Skin (Poor)", "alligator_pelt_poor"},
    [-1475338121] = {"Alligator Skin (Pristine)", "alligator_pelt_pristine"},
    --MULTI LEGENDARIES
    [1418435161] = {"Ridgeback Spirit Bear Pelt", "spirit_bear_pelt"},
    [1181154860] = {"Owiza Bear Pelt", "owiza_bear_pelt"},
    [1511236969] = {"Golden Spirit Bear Pelt", "golden_bear_pelt"},
    
    [-1621144167] = {"Sungator Skin", "sungator_pelt"},
    [-1061253029] = {"Banded Allligator Skin", "banded_gator_pelt"},
    [-1924159110] = {"Teca Gator Skin", "teca_gator_pelt"},

    [-1787430524] = {"Night Beaver Pelt", "night_beaver_pelt"},
    [-251416414] = {"Moon Beaver Pelt", "moon_beaver_pelt"},
    [121494806] = {"Zizi Beaver Pelt", "zizi_beaver_pelt"},

    [-591844128] = {"Rutile Horn Ram Pelt", "rutile_ram_pelt"},
    [-675142890] = {"Gabbro Horn Ram Pelt", "gabbro_ram_pelt"},
    [-906131571] = {"Chalk Horn Ram Pelt", "chalk_ram_pelt"},

    [-940052481] = {"Icahi Boar Pelt", "icahi_boar_pelt"},
    [-1249752300] = {"Wakpa Boar Pelt", "wakpa_boar_pelt"},
    [-1572330336] = {"Cogi Boar Pelt", "cogi_boar_pelt"},

    [-1218522879] = {"Snowy Buck Pelt", "snowy_buck_pelt"},
    [-308200059] = {"Mudrunner Buck Pelt", "mudrunner_buck_pelt"},
    [923422806] = {"Shadow Buck Pelt", "shadow_buck_pelt"},

    [-260181673] = {"Tatanka Bison Pelt", "tatanka_bison_pelt"},
    [-857265622] = {"Payta Bison Pelt", "payta_bison_pelt"},
    [-1087205695] = {"Winyan Bison Pelt", "winyan_bison_pelt"},

    [219794592] = {"Sapa Cougar Pelt", "sapa_cougar_pelt"},
    [397926876] = {"Maza Cougar Pelt", "maza_cougar_pelt"},
    [832214437] = {"Iguga Cougar Pelt", "iguga_cougar_pelt"},

    [1009802015] = {"Milk Coyote Pelt", "milk_coyote_pelt"},
    [1728819413] = {"Midnight Paw Coyote Pelt", "midnightpaw_coyote_pelt"},
    [-1061362634] = {"Red Streak Coyote Pelt", "redstreak_coyote_pelt"},

    [1276143905] = {"Ota Fox Pelt", "ota_fox_pelt"},
    [-1262044528] = {"Marble Fox Pelt", "marble_fox_pelt"},
    [-963027403] = {"Cross Fox Pelt", "cross_fox_pelt"},
    
    [-1195518864] = {"Ozula Elk Pelt", "ozula_elk_pelt"},
    [-159428614] = {"Inahme Elk Pelt", "inahme_elk_pelt"},
    [-420237085] = {"Katata Elk Pelt", "katata_elk_pelt"},

    [739090883] = {"Snowflake Moose Pelt", "snowflake_moose_pelt"},
    [1043121665] = {"Knight Moose Pelt", "knight_moose_pelt"},
    [-634716689] = {"Ruddy Moose Pelt", "ruddy_moose_pelt"},

    [1600479946] = {"Iwakta Panther Pelt", "iwakta_panther_pelt"},
    [836208559] = {"Ghost Panther Pelt", "ghost_panther_pelt"},
    [2088901891] = {"Nightwalker Panther Pelt", "nightwalker_panther_pelt"},

    [-1946740647] = {"Emerald Wolf Pelt", "emerald_wolf_pelt"},
    [-907373381] = {"Moonstone Wolf Pelt", "moonstone_wolf_pelt"},
    [-1548204069] = {"Onyx Wolf Pelt", "onyx_wolf_pelt"},
}

Config.ItemHash = {--items can be sold in shops and used to create pelt
    ["alligator_s_pelt_pristine"] = {hash = `provision_alligator_skin_pristine`, model = `p_cs_crocskin_medium_roll`, type = `CARRIABLE_ANIMAL_SKIN_ML`, price = 15},
    ["alligator_s_pelt_poor"] = {hash = `provision_alligator_skin_poor`, model = `p_cs_crocskin_medium_roll`, type = `CARRIABLE_ANIMAL_SKIN_ML`, price = 5},
    ["alligator_s_pelt_good"] = {hash = `provision_alligator_skin`, model = `p_cs_crocskin_medium_roll`, type = `CARRIABLE_ANIMAL_SKIN_ML`, price = 8},
    ["snowy_buck_pelt"] = {hash = -1218522879, model = `P_CS_PELT_LARGE`, type = `CARRIABLE_ANIMAL_SKIN_L`, price = 50},
    ["moose_pelt_good"] = {hash = `PROVISION_MOOSE_FUR`, model = `p_cs_pelt_xlarge`, type = `CARRIABLE_XL_BUFFALO_SKIN`, price = 20},
    ["cow_pelt_poor"] = {hash = `PROVISION_COW_HIDE_POOR`, model = `p_cs_pelt_xlarge`, type = `CARRIABLE_XL_BUFFALO_SKIN`, price = 5},
    ["goat_pelt_pristine"] = {hash = `PROVISION_GOAT_HAIR_PRISTINE`, model = `P_CS_PELT_LARGE`, type = `CARRIABLE_ANIMAL_SKIN_L`, price = 5},
    ["legendary_elk_pelt"] = {hash = `PROVISION_ELK_LEGENDARY_FUR_PRISTINE`, model = `p_cs_pelt_elklegendary`, type = `CARRIABLE_XL_BUFFALO_SKIN`, price = 50},
    ["black_bear_pelt_poor"] = {hash = `PROVISION_BLACK_BEAR_FUR_POOR`, model = `p_cs_blackbearskin_medlarge`, type = `CARRIABLE_XL_BUFFALO_SKIN`, price = 10},
    ["beaver_pelt_poor"] = {hash = `PROVISION_BEAVER_FUR_POOR`, model = `P_CS_PELT_MEDLARGE`, type = `CARRIABLE_ANIMAL_SKIN_ML`, price = 5},
    ["legendary_bear_pelt"] = {hash = `PROVISION_BEAR_LEGENDARY_FUR_PRISTINE`, model = `p_cs_pelt_xlarge`, type = `CARRIABLE_XL_BUFFALO_SKIN`, price = 50},
    ["zizi_beaver_pelt"] = {hash = 121494806, model = `P_CS_PELT_MEDLARGE`, type = `CARRIABLE_ANIMAL_SKIN_ML`, price = 50},
    ["bear_pelt_pristine"] = {hash = `PROVISION_BEAR_FUR_PRISTINE`, model = `p_cs_pelt_xlarge_bear`, type = `CARRIABLE_XL_BUFFALO_SKIN`, price = 30},
    ["bear_pelt_good"] = {hash = `PROVISION_BEAR_FUR`, model = `p_cs_pelt_xlarge_bear`, type = `CARRIABLE_XL_BUFFALO_SKIN`, price = 20},
    ["cougar_pelt_good"] = {hash = `PROVISION_COUGAR_FUR`, model = `P_CS_PELT_LARGE`, type = `CARRIABLE_ANIMAL_SKIN_L`, price = 30},
    ["cow_pelt_pristine"] = {hash = `PROVISION_COW_HIDE_PRISTINE`, model = `p_cs_pelt_xlarge`, type = `CARRIABLE_XL_BUFFALO_SKIN`, price = 10},
    ["buck_pelt_good"] = {hash = `PROVISION_BUCK_FUR`, model = `P_CS_PELT_LARGE`, type = `CARRIABLE_ANIMAL_SKIN_L`, price = 10},
    ["coyote_pelt_poor"] = {hash = `PROVISION_COYOTE_FUR_POOR`, model = `P_CS_PELT_MEDLARGE`, type = `CARRIABLE_ANIMAL_SKIN_ML`, price = 2},
    ["ram_pelt_pristine"] = {hash = `PROVISION_RAM_HIDE_PRISTINE`, model = `P_CS_PELT_LARGE`, type = `CARRIABLE_ANIMAL_SKIN_L`, price = 8},
    ["payta_bison_pelt"] = {hash = -857265622, model = `P_CS_PELT_LARGE`, type = `CARRIABLE_ANIMAL_SKIN_L`, price = 50},
    ["owiza_bear_pelt"] = {hash = 1181154860, model = `p_cs_pelt_xlarge_bearlegendary`, type = `CARRIABLE_XL_BUFFALO_SKIN`, price = 50},
    ["panther_pelt_poor"] = {hash = `PROVISION_PANTHER_FUR_POOR`, model = `P_CS_PELT_LARGE`, type = `CARRIABLE_ANIMAL_SKIN_L`, price = 10},
    ["legendary_panther_pelt"] = {hash = `PROVISION_PANTHER_LEGENDARY_FUR_PRISTINE`, model = `P_CS_PELT_LARGE`, type = `CARRIABLE_ANIMAL_SKIN_L`, price = 50},
    ["cross_fox_pelt"] = {hash = -963027403, model = `P_CS_PELT_MEDLARGE`, type = `CARRIABLE_ANIMAL_SKIN_ML`, price = 50},
    ["redstreak_coyote_pelt"] = {hash = -1061362634, model = `P_CS_PELT_MEDLARGE`, type = `CARRIABLE_ANIMAL_SKIN_ML`, price = 50},
    ["cow_pelt_good"] = {hash = `PROVISION_COW_HIDE`, model = `p_cs_pelt_xlarge`, type = `CARRIABLE_XL_BUFFALO_SKIN`, price = 7},
    ["panther_pelt_pristine"] = {hash = `PROVISION_PANTHER_FUR_PRISTINE`, model = `P_CS_PELT_LARGE`, type = `CARRIABLE_ANIMAL_SKIN_L`, price = 30},
    ["bull_pelt_poor"] = {hash = `PROVISION_BULL_HIDE_POOR`, model = `P_CS_PELT_LARGE`, type = `CARRIABLE_ANIMAL_SKIN_L`, price = 5},
    ["legendary_pronghorn_pelt"] = {hash = `PROVISION_PRONGHORN_LEGENDARY_FUR_PRISTINE`, model = `P_CS_PELT_LARGE`, type = `CARRIABLE_ANIMAL_SKIN_L`, price = 50},
    ["legendary_beaver_pelt"] = {hash = `PROVISION_BEAVER_LEGENDARY_FUR_PRISTINE`, model = `P_CS_PELT_MEDLARGE`, type = `CARRIABLE_ANIMAL_SKIN_ML`, price = 50},
    ["buck_pelt_pristine"] = {hash = `PROVISION_BUCK_FUR_PRISTINE`, model = `P_CS_PELT_LARGE`, type = `CARRIABLE_ANIMAL_SKIN_L`, price = 10},
    ["elk_pelt_poor"] = {hash = `PROVISION_ELK_FUR_POOR`, model = `p_cs_pelt_xlarge_elk`, type = `CARRIABLE_XL_BUFFALO_SKIN`, price = 5},
    ["legendary_buck_pelt"] = {hash = `PROVISION_BUCK_LEGENDARY_FUR_PRISTINE`, model = `P_CS_PELT_LARGE`, type = `CARRIABLE_ANIMAL_SKIN_L`, price = 50},
    ["base_pelt_good"] = {hash = `PROVISION_DEER_HIDE`, model = `P_CS_PELT_LARGE`, type = `CARRIABLE_ANIMAL_SKIN_L`, price = 2},
    ["beaver_pelt_pristine"] = {hash = `PROVISION_BEAVER_FUR_PRISTINE`, model = `P_CS_PELT_MEDLARGE`, type = `CARRIABLE_ANIMAL_SKIN_ML`, price = 10},
    ["tatanka_bison_pelt"] = {hash = -260181673, model = `P_CS_PELT_LARGE`, type = `CARRIABLE_ANIMAL_SKIN_L`, price = 50},
    ["bull_pelt_good"] = {hash = `PROVISION_BULL_HIDE`, model = `P_CS_PELT_LARGE`, type = `CARRIABLE_ANIMAL_SKIN_L`, price = 10},
    ["spirit_bear_pelt"] = {hash = 1418435161, model = `p_cs_pelt_xlarge_bearlegendary`, type = `CARRIABLE_XL_BUFFALO_SKIN`, price = 7},
    ["banded_gator_pelt"] = {hash = -1061253029, model = `P_CS_PELT_LARGE`, type = `CARRIABLE_ANIMAL_SKIN_L`, price = 50},
    ["fox_pelt_poor"] = {hash = `PROVISION_FOX_FUR_POOR`, model = `P_CS_PELT_MEDLARGE`, type = `CARRIABLE_ANIMAL_SKIN_ML`, price = 5},
    ["ram_pelt_poor"] = {hash = `PROVISION_RAM_HIDE_POOR`, model = `P_CS_PELT_LARGE`, type = `CARRIABLE_ANIMAL_SKIN_L`, price = 5},
    ["sheep_pelt_pristine"] = {hash = `PROVISION_SHEEP_WOOL_PRISTINE`, model = `P_CS_PELT_LARGE`, type = `CARRIABLE_ANIMAL_SKIN_L`, price = 9},
    ["goat_pelt_good"] = {hash = `PROVISION_GOAT_HAIR`, model = `P_CS_PELT_LARGE`, type = `CARRIABLE_ANIMAL_SKIN_L`, price = 7},
    ["elk_pelt_pristine"] = {hash = `PROVISION_ELK_FUR_PRISTINE`, model = `p_cs_pelt_xlarge_elk`, type = `CARRIABLE_XL_BUFFALO_SKIN`, price = 20},
    ["golden_bear_pelt"] = {hash = 1511236969, model = `p_cs_pelt_xlarge_bearlegendary`, type = `CARRIABLE_XL_BUFFALO_SKIN`, price = 50},
    ["ozula_elk_pelt"] = {hash = -1195518864, model = `p_cs_pelt_elklegendary`, type = `CARRIABLE_XL_BUFFALO_SKIN`, price = 50},
    ["boar_pelt_poor"] = {hash = `PROVISION_BOAR_SKIN_POOR`, model = `P_CS_PELT_LARGE`, type = `CARRIABLE_ANIMAL_SKIN_L`, price = 5},
    ["alligator_pelt_pristine"] = {hash = -1475338121, model = `p_cs_pelt_xlarge_alligator`, type = `CARRIABLE_XL_BUFFALO_SKIN`, price = 10},
    ["teca_gator_pelt"] = {hash = -1924159110, model = `P_CS_PELT_LARGE`, type = `CARRIABLE_ANIMAL_SKIN_L`, price = 50},
    ["coyote_pelt_pristine"] = {hash = `PROVISION_COYOTE_FUR_PRISTINE`, model = `P_CS_PELT_MEDLARGE`, type = `CARRIABLE_ANIMAL_SKIN_ML`, price = 9},
    ["night_beaver_pelt"] = {hash = -1787430524, model = `P_CS_PELT_MEDLARGE`, type = `CARRIABLE_ANIMAL_SKIN_ML`, price = 50},
    ["moose_pelt_poor"] = {hash = `PROVISION_MOOSE_FUR_POOR`, model = `p_cs_pelt_xlarge`, type = `CARRIABLE_XL_BUFFALO_SKIN`, price = 5},
    ["buck_pelt_poor"] = {hash = `PROVISION_BUCK_FUR_POOR`, model = `P_CS_PELT_LARGE`, type = `CARRIABLE_ANIMAL_SKIN_L`, price = 5},
    ["black_bear_pelt_good"] = {hash = `PROVISION_BLACK_BEAR_FUR`, model = `p_cs_blackbearskin_medlarge`, type = `CARRIABLE_XL_BUFFALO_SKIN`, price = 10},
    ["chalk_ram_pelt"] = {hash = -906131571, model = `P_CS_PELT_LARGE`, type = `CARRIABLE_ANIMAL_SKIN_L`, price = 50},
    ["pronghorn_pelt_good"] = {hash = `PROVISION_PRONGHORN_FUR`, model = `P_CS_PELT_LARGE`, type = `CARRIABLE_ANIMAL_SKIN_L`, price = 7},
    ["legendary_wolf_pelt"] = {hash = `PROVISION_WOLF_LEGENDARY_FUR_PRISTINE`, model = `P_CS_PELT_LARGE`, type = `CARRIABLE_ANIMAL_SKIN_L`, price = 50},
    ["black_bear_pelt_pristine"] = {hash = `PROVISION_BLACK_BEAR_FUR_PRISTINE`, model = `p_cs_blackbearskin_medlarge`, type = `CARRIABLE_XL_BUFFALO_SKIN`, price = 20},
    ["ox_pelt_good"] = {hash = `PROVISION_OXEN_HIDE`, model = `p_cs_pelt_xlarge`, type = `CARRIABLE_XL_BUFFALO_SKIN`, price = 7},
    ["sungator_pelt"] = {hash = -1621144167, model = `P_CS_PELT_LARGE`, type = `CARRIABLE_ANIMAL_SKIN_L`, price = 50},
    ["buffalo_pelt_pristine"] = {hash = `PROVISION_BUFFALO_FUR_PRISTINE`, model = `p_cs_pelt_xlarge_buffalo`, type = `CARRIABLE_XL_BUFFALO_SKIN`, price = 10},
    ["cogi_boar_pelt"] = {hash = -1572330336, model = `P_CS_PELT_LARGE`, type = `CARRIABLE_ANIMAL_SKIN_L`, price = 50},
    ["moon_beaver_pelt"] = {hash = -251416414, model = `P_CS_PELT_MEDLARGE`, type = `CARRIABLE_ANIMAL_SKIN_ML`, price = 50},
    ["legendary_fox_pelt"] = {hash = `PROVISION_FOX_LEGENDARY_FUR_PRISTINE`, model = `P_CS_PELT_MEDLARGE`, type = `CARRIABLE_ANIMAL_SKIN_ML`, price = 50},
    ["base_pelt_pristine"] = {hash = `PROVISION_DEER_HIDE_PRISTINE`, model = `P_CS_PELT_LARGE`, type = `CARRIABLE_ANIMAL_SKIN_L`, price = 5},
    ["bull_pelt_pristine"] = {hash = `PROVISION_BULL_HIDE_PRISTINE`, model = `P_CS_PELT_LARGE`, type = `CARRIABLE_ANIMAL_SKIN_L`, price = 10},
    ["wolf_pelt_poor"] = {hash = `PROVISION_WOLF_FUR_POOR`, model = `p_cs_pelt_wolf`, type = `CARRIABLE_ANIMAL_SKIN_L`, price = 5},
    ["pronghorn_pelt_poor"] = {hash = `PROVISION_PRONGHORN_FUR_POOR`, model = `P_CS_PELT_LARGE`, type = `CARRIABLE_ANIMAL_SKIN_L`, price = 5},
    ["ghost_panther_pelt"] = {hash = 836208559, model = `P_CS_PELT_LARGE`, type = `CARRIABLE_ANIMAL_SKIN_L`, price = 50},
    ["cougar_pelt_pristine"] = {hash = `PROVISION_COUGAR_FUR_PRISTINE`, model = `P_CS_PELT_LARGE`, type = `CARRIABLE_ANIMAL_SKIN_L`, price = 30},
    ["boar_pelt_good"] = {hash = `PROVISION_BOAR_SKIN`, model = `P_CS_PELT_LARGE`, type = `CARRIABLE_ANIMAL_SKIN_L`, price = 7},
    ["moonstone_wolf_pelt"] = {hash = -907373381, model = `P_CS_PELT_LARGE`, type = `CARRIABLE_ANIMAL_SKIN_L`, price = 50},
    ["coyote_pelt_good"] = {hash = `PROVISION_COYOTE_FUR`, model = `P_CS_PELT_MEDLARGE`, type = `CARRIABLE_ANIMAL_SKIN_ML`, price = 5},
    ["legendary_cougar_pelt"] = {hash = `PROVISION_COUGAR_LEGENDARY_FUR_PRISTINE`, model = `P_CS_PELT_LARGE`, type = `CARRIABLE_ANIMAL_SKIN_L`, price = 50},
    ["snowflake_moose_pelt"] = {hash = 739090883, model = `p_cs_pelt_xlarge`, type = `CARRIABLE_XL_BUFFALO_SKIN`, price = 50},
    ["onyx_wolf_pelt"] = {hash = -1548204069, model = `P_CS_PELT_LARGE`, type = `CARRIABLE_ANIMAL_SKIN_L`, price = 50},
    ["emerald_wolf_pelt"] = {hash = -1946740647, model = `P_CS_PELT_LARGE`, type = `CARRIABLE_ANIMAL_SKIN_L`, price = 50},
    ["nightwalker_panther_pelt"] = {hash = 2088901891, model = `P_CS_PELT_LARGE`, type = `CARRIABLE_ANIMAL_SKIN_L`, price = 50},
    ["goat_pelt_poor"] = {hash = `PROVISION_GOAT_HAIR_POOR`, model = `P_CS_PELT_LARGE`, type = `CARRIABLE_ANIMAL_SKIN_L`, price = 5},
    ["javelina_pelt_good"] = {hash = `PROVISION_JAVELINA_SKIN`, model = `P_CS_PELT_LARGE`, type = `CARRIABLE_ANIMAL_SKIN_L`, price = 7},
    ["fox_pelt_good"] = {hash = `PROVISION_FOX_FUR`, model = `P_CS_PELT_MEDLARGE`, type = `CARRIABLE_ANIMAL_SKIN_ML`, price = 7},
    ["ox_pelt_pristine"] = {hash = `PROVISION_OXEN_HIDE_PRISTINE`, model = `p_cs_pelt_xlarge`, type = `CARRIABLE_XL_BUFFALO_SKIN`, price = 10},
    ["buffalo_pelt_good"] = {hash = `PROVISION_BUFFALO_FUR`, model = `p_cs_pelt_xlarge_buffalo`, type = `CARRIABLE_XL_BUFFALO_SKIN`, price = 15},
    ["iwakta_panther_pelt"] = {hash = 1600479946, model = `P_CS_PELT_LARGE`, type = `CARRIABLE_ANIMAL_SKIN_L`, price = 50},
    ["legendary_moose_pelt"] = {hash = `PROVISION_MOOSE_LEGENDARY_FUR_PRISTINE`, model = `p_cs_pelt_xlarge`, type = `CARRIABLE_XL_BUFFALO_SKIN`, price = 50},
    ["wolf_pelt_pristine"] = {hash = `PROVISION_WOLF_FUR_PRISTINE`, model = `p_cs_pelt_wolf`, type = `CARRIABLE_ANIMAL_SKIN_L`, price = 10},
    ["knight_moose_pelt"] = {hash = 1043121665, model = `p_cs_pelt_xlarge`, type = `CARRIABLE_XL_BUFFALO_SKIN`, price = 50},
    ["katata_elk_pelt"] = {hash = -420237085, model = `p_cs_pelt_elklegendary`, type = `CARRIABLE_XL_BUFFALO_SKIN`, price = 50},
    ["elk_pelt_good"] = {hash = `PROVISION_ELK_FUR`, model = `p_cs_pelt_xlarge_elk`, type = `CARRIABLE_XL_BUFFALO_SKIN`, price = 10},
    ["sheep_pelt_good"] = {hash = `PROVISION_SHEEP_WOOL`, model = `P_CS_PELT_LARGE`, type = `CARRIABLE_ANIMAL_SKIN_L`, price = 7},
    ["bear_pelt_poor"] = {hash = `PROVISION_BEAR_FUR_POOR`, model = `p_cs_pelt_xlarge_bear`, type = `CARRIABLE_XL_BUFFALO_SKIN`, price = 5},
    ["marble_fox_pelt"] = {hash = -1262044528, model = `P_CS_PELT_MEDLARGE`, type = `CARRIABLE_ANIMAL_SKIN_ML`, price = 50},
    ["pig_pelt_good"] = {hash = `PROVISION_PIG_SKIN`, model = `P_CS_PELT_LARGE`, type = `CARRIABLE_ANIMAL_SKIN_L`, price = 7},
    ["ota_fox_pelt"] = {hash = 1276143905, model = `P_CS_PELT_MEDLARGE`, type = `CARRIABLE_ANIMAL_SKIN_ML`, price = 50},
    ["javelina_pelt_poor"] = {hash = `PROVISION_JAVELINA_SKIN_POOR`, model = `P_CS_PELT_LARGE`, type = `CARRIABLE_ANIMAL_SKIN_L`, price = 5},
    ["buffalo_pelt_poor"] = {hash = `PROVISION_BUFFALO_FUR_POOR`, model = `p_cs_pelt_xlarge_buffalo`, type = `CARRIABLE_XL_BUFFALO_SKIN`, price = 5},
    ["pig_pelt_poor"] = {hash = `PROVISION_PIG_SKIN_POOR`, model = `P_CS_PELT_LARGE`, type = `CARRIABLE_ANIMAL_SKIN_L`, price = 5},
    ["moose_pelt_pristine"] = {hash = `PROVISION_MOOSE_FUR_PRISTINE`, model = `p_cs_pelt_xlarge`, type = `CARRIABLE_XL_BUFFALO_SKIN`, price = 30},
    ["beaver_pelt_good"] = {hash = `PROVISION_BEAVER_FUR`, model = `P_CS_PELT_MEDLARGE`, type = `CARRIABLE_ANIMAL_SKIN_ML`, price = 7},
    ["midnightpaw_coyote_pelt"] = {hash = 1728819413, model = `P_CS_PELT_MEDLARGE`, type = `CARRIABLE_ANIMAL_SKIN_ML`, price = 50},
    ["rutile_ram_pelt"] = {hash = -591844128, model = `P_CS_PELT_LARGE`, type = `CARRIABLE_ANIMAL_SKIN_L`, price = 50},
    ["milk_coyote_pelt"] = {hash = 1009802015, model = `P_CS_PELT_MEDLARGE`, type = `CARRIABLE_ANIMAL_SKIN_ML`, price = 50},
    ["iguga_cougar_pelt"] = {hash = 832214437, model = `P_CS_PELT_LARGE`, type = `CARRIABLE_ANIMAL_SKIN_L`, price = 50},
    ["panther_pelt_good"] = {hash = `PROVISION_PANTHER_FUR`, model = `P_CS_PELT_LARGE`, type = `CARRIABLE_ANIMAL_SKIN_L`, price = 10},
    ["maza_cougar_pelt"] = {hash = 397926876, model = `P_CS_PELT_LARGE`, type = `CARRIABLE_ANIMAL_SKIN_L`, price = 50},
    ["sapa_cougar_pelt"] = {hash = 219794592, model = `P_CS_PELT_LARGE`, type = `CARRIABLE_ANIMAL_SKIN_L`, price = 50},
    ["winyan_bison_pelt"] = {hash = -1087205695, model = `p_cs_pelt_xlarge`, type = `CARRIABLE_XL_BUFFALO_SKIN`, price = 50},
    ["shadow_buck_pelt"] = {hash = 923422806, model = `P_CS_PELT_LARGE`, type = `CARRIABLE_ANIMAL_SKIN_L`, price = 50},
    ["mudrunner_buck_pelt"] = {hash = -308200059, model = `P_CS_PELT_LARGE`, type = `CARRIABLE_ANIMAL_SKIN_L`, price = 50},
    ["wakpa_boar_pelt"] = {hash = -1249752300, model = `P_CS_PELT_LARGE`, type = `CARRIABLE_ANIMAL_SKIN_L`, price = 50},
    ["alligator_pelt_poor"] = {hash = -1243878166, model = `p_cs_pelt_xlarge_alligator`, type = `CARRIABLE_XL_BUFFALO_SKIN`, price = 5},
    ["legendary_boar_pelt"] = {hash = `PROVISION_BOAR_LEGENDARY_SKIN_PRISTINE`, model = `P_CS_PELT_LARGE`, type = `CARRIABLE_ANIMAL_SKIN_L`, price = 50},
    ["cougar_pelt_poor"] = {hash = `PROVISION_COUGAR_FUR_POOR`, model = `P_CS_PELT_LARGE`, type = `CARRIABLE_ANIMAL_SKIN_L`, price = 5},
    ["gabbro_ram_pelt"] = {hash = -675142890, model = `P_CS_PELT_LARGE`, type = `CARRIABLE_ANIMAL_SKIN_L`, price = 50},
    ["wolf_pelt_good"] = {hash = `PROVISION_WOLF_FUR`, model = `p_cs_pelt_wolf`, type = `CARRIABLE_ANIMAL_SKIN_L`, price = 7},
    ["ruddy_moose_pelt"] = {hash = -634716689, model = `p_cs_pelt_xlarge`, type = `CARRIABLE_XL_BUFFALO_SKIN`, price = 50},
    ["white_bison_pelt"] = {hash = `PROVISION_WHITE_BUFFALO_LEGENDARY_FUR_PRISTINE`, model = `p_cs_pelt_xlarge_wbuffalo`, type = `CARRIABLE_XL_BUFFALO_SKIN`, price = 50},
    ["takanta_bison_pelt"] = {hash = `PROVISION_TAKANTA_BUFFALO_LEGENDARY_FUR_PRISTINE`, model = `p_cs_pelt_xlarge_tbuffalo`, type = `CARRIABLE_XL_BUFFALO_SKIN`, price = 50},
    ["sheep_pelt_poor"] = {hash = `PROVISION_SHEEP_WOOL_POOR`, model = `p_cs_pelt_xlarge`, type = `CARRIABLE_XL_BUFFALO_SKIN`, price = 5},
    ["legendary_ram_pelt"] = {hash = `PROVISION_RAM_LEGENDARY_HIDE_PRISTINE`, model = `P_CS_PELT_LARGE`, type = `CARRIABLE_ANIMAL_SKIN_L`, price = 50},
    ["base_pelt_poor"] = {hash = `PROVISION_DEER_HIDE_POOR`, model = `P_CS_PELT_LARGE`, type = `CARRIABLE_ANIMAL_SKIN_L`, price = 5},
    ["ram_pelt_good"] = {hash = `PROVISION_RAM_HIDE`, model = `P_CS_PELT_LARGE`, type = `CARRIABLE_ANIMAL_SKIN_L`, price = 7},
    ["boar_pelt_pristine"] = {hash = `PROVISION_BOAR_SKIN_PRISTINE`, model = `P_CS_PELT_LARGE`, type = `CARRIABLE_ANIMAL_SKIN_L`, price = 10},
    ["fox_pelt_pristine"] = {hash = `PROVISION_FOX_FUR_PRISTINE`, model = `P_CS_PELT_MEDLARGE`, type = `CARRIABLE_ANIMAL_SKIN_ML`, price = 10},
    ["pronghorn_pelt_pristine"] = {hash = `PROVISION_PRONGHORN_FUR_PRISTINE`, model = `P_CS_PELT_LARGE`, type = `CARRIABLE_ANIMAL_SKIN_L`, price = 10},
    ["inahme_elk_pelt"] = {hash = -159428614, model = `p_cs_pelt_elklegendary`, type = `CARRIABLE_XL_BUFFALO_SKIN`, price = 50},
    ["ox_pelt_poor"] = {hash = `PROVISION_OXEN_HIDE_POOR`, model = `p_cs_pelt_xlarge`, type = `CARRIABLE_XL_BUFFALO_SKIN`, price = 5},
    ["javelina_pelt_pristine"] = {hash = `PROVISION_JAVELINA_SKIN_PRISTINE`, model = `P_CS_PELT_LARGE`, type = `CARRIABLE_ANIMAL_SKIN_L`, price = 10},
    ["pig_pelt_pristine"] = {hash = `PROVISION_PIG_SKIN_PRISTINE`, model = `P_CS_PELT_LARGE`, type = `CARRIABLE_ANIMAL_SKIN_L`, price = 10},
    ["legendary_coyote_pelt"] = {hash = `PROVISION_COYOTE_LEGENDARY_FUR_PRISTINE`, model = `P_CS_PELT_MEDLARGE`, type = `CARRIABLE_ANIMAL_SKIN_ML`, price = 50},
    ["icahi_boar_pelt"] = {hash = -940052481, model = `P_CS_PELT_LARGE`, type = `CARRIABLE_ANIMAL_SKIN_L`, price = 50},
}
