INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('panther_pelt_good', 'Panther Fur (Good)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('pig_pelt_poor', 'Pig Skin (Poor)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('ghost_panther_pelt', 'Ghost Panther Pelt', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('alligator_pelt_pristine', 'Alligator Skin (Pristine)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('marble_fox_pelt', 'Marble Fox Pelt', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('buck_pelt_poor', 'Buck Fur (Poor)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('legendary_beaver_pelt', 'Legendary Beaver Fur', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('winyan_bison_pelt', 'Winyan Bison Pelt', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('cow_pelt_poor', 'Cow Hide (Poor)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('coyote_pelt_poor', 'Coyote Fur (Poor)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('gabbro_ram_pelt', 'Gabbro Horn Ram Pelt', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('alligator_s_pelt_good', 'Small Alligator Skin (Good)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('spirit_bear_pelt', 'Ridgeback Spirit Bear Pelt', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('panther_pelt_pristine', 'Panther Fur (Pristine)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('moose_pelt_good', 'Moose Fur (Good)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('cougar_pelt_poor', 'Cougar Fur (Poor)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('goat_pelt_pristine', 'Goat Hair (Pristine)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('pronghorn_pelt_pristine', 'Pronghorn Fur (Pristine)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('emerald_wolf_pelt', 'Emerald Wolf Pelt', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('knight_moose_pelt', 'Knight Moose Pelt', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('rutile_ram_pelt', 'Rutile Horn Ram Pelt', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('legendary_wolf_pelt', 'Legendary Wolf Fur', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('sungator_pelt', 'Sungator Skin', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('ox_pelt_poor', 'Oxen Hide (Poor)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('buck_pelt_pristine', 'Buck Fur (Pristine)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('wolf_pelt_poor', 'Wolf Fur (Poor)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('sapa_cougar_pelt', 'Sapa Cougar Pelt', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('alligator_s_pelt_pristine', 'Small Alligator Skin (Pristine)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('payta_bison_pelt', 'Payta Bison Pelt', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('sheep_pelt_poor', 'Sheep Wool (Poor)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('pronghorn_pelt_good', 'Pronghorn Fur (Good)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('black_bear_pelt_pristine', 'Black Bear Fur (Pristine)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('golden_bear_pelt', 'Golden Spirit Bear Pelt', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('bear_pelt_poor', 'Bear Fur (Poor)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('base_pelt_poor', 'Hide (Poor)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('ruddy_moose_pelt', 'Ruddy Moose Pelt', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('teca_gator_pelt', 'Teca Gator Skin', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('buffalo_pelt_poor', 'Buffalo Fur (Poor)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('ozula_elk_pelt', 'Ozula Elk Pelt', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('legendary_ram_pelt', 'Legendary Ram Hide', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('goat_pelt_poor', 'Goat Hair (Poor)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('cogi_boar_pelt', 'Cogi Boar Pelt', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('fox_pelt_pristine', 'Fox Fur (Pristine)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('onyx_wolf_pelt', 'Onyx Wolf Pelt', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('chalk_ram_pelt', 'Chalk Horn Ram Pelt', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('cow_pelt_good', 'Cow Hide (Good)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('bull_pelt_poor', 'Bull Hide (Poor)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('bull_pelt_good', 'Bull Hide (Good)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('sheep_pelt_good', 'Sheep Wool (Good)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('alligator_pelt_poor', 'Alligator Skin (Poor)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('midnightpaw_coyote_pelt', 'Midnight Paw Coyote Pelt', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('ram_pelt_good', 'Ram Hide (Good)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('ram_pelt_pristine', 'Ram Hide (Pristine)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('cougar_pelt_good', 'Cougar Fur (Good)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('base_pelt_pristine', 'Hide (Pristine)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('cross_fox_pelt', 'Cross Fox Pelt', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('legendary_panther_pelt', 'Legendary Panther Fur', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('moose_pelt_poor', 'Moose Fur (Poor)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('takanta_bison_pelt', 'Takanta Buffalo Fur', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('banded_gator_pelt', 'Banded Allligator Skin', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('snowflake_moose_pelt', 'Snowflake Moose Pelt', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('coyote_pelt_good', 'Coyote Fur (Good)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('elk_pelt_good', 'Elk Fur (Good)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('iwakta_panther_pelt', 'Iwakta Panther Pelt', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('owiza_bear_pelt', 'Owiza Bear Pelt', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('redstreak_coyote_pelt', 'Red Streak Coyote Pelt', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('night_beaver_pelt', 'Night Beaver Pelt', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('legendary_moose_pelt', 'Legendary Moose Fur', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('milk_coyote_pelt', 'Milk Coyote Pelt', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('pig_pelt_good', 'Pig Skin (Good)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('boar_pelt_poor', 'Boar Skin (Poor)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('buck_pelt_good', 'Buck Fur (Good)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('bear_pelt_good', 'Bear Fur (Good)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('bull_pelt_pristine', 'Bull Hide (Pristine)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('javelina_pelt_pristine', 'Javelina Skin (Pristine)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('wolf_pelt_pristine', 'Wolf Fur (Pristine)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('white_bison_pelt', 'Whtie Buffalo Fur', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('tatanka_bison_pelt', 'Tatanka Bison Pelt', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('alligator_s_pelt_poor', 'Small Alligator Skin (Poor)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('panther_pelt_poor', 'Panther Fur (Poor)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('beaver_pelt_poor', 'Beaver Fur (Poor)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('fox_pelt_good', 'Fox Fur (Good)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('cougar_pelt_pristine', 'Cougar Fur (Pristine)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('legendary_fox_pelt', 'Legendary Fox Fur', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('ram_pelt_poor', 'Ram Hide (Poor)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('bear_pelt_pristine', 'Bear Fur (Pristine)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('wakpa_boar_pelt', 'Wakpa Boar Pelt', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('elk_pelt_poor', 'Elk Fur (Poor)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('ox_pelt_pristine', 'Oxen Hide (Pristine)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('nightwalker_panther_pelt', 'Nightwalker Panther Pelt', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('legendary_buck_pelt', 'Legendary Buck Fur', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('shadow_buck_pelt', 'Shadow Buck Pelt', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('zizi_beaver_pelt', 'Zizi Beaver Pelt', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('legendary_pronghorn_pelt', 'Legendary Pronghorn Fur', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('cow_pelt_pristine', 'Cow Hide (Pristine)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('javelina_pelt_poor', 'Javelina Skin (Poor)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('legendary_cougar_pelt', 'Legendary Cougar Fur', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('black_bear_pelt_poor', 'Black Bear Fur (Poor)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('pig_pelt_pristine', 'Pig Skin (Pristine)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('legendary_bear_pelt', 'Legendary Bear Fur', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('elk_pelt_pristine', 'Elk Fur (Pristine)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('icahi_boar_pelt', 'Icahi Boar Pelt', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('legendary_boar_pelt', 'Legendary Boar Skin', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('base_pelt_good', 'Hide (Good)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('legendary_elk_pelt', 'Legendary Elk Fur', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('inahme_elk_pelt', 'Inahme Elk Pelt', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('ox_pelt_good', 'Oxen Hide (Good)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('moose_pelt_pristine', 'Moose Fur (Pristine)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('sheep_pelt_pristine', 'Sheep Wool (Pristine)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('buffalo_pelt_pristine', 'Buffalo Fur (Pristine)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('snowy_buck_pelt', 'Snowy Buck Pelt', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('boar_pelt_good', 'Boar Skin (Good)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('iguga_cougar_pelt', 'Iguga Cougar Pelt', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('mudrunner_buck_pelt', 'Mudrunner Buck Pelt', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('buffalo_pelt_good', 'Buffalo Fur (Good)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('beaver_pelt_pristine', 'Beaver Fur (Pristine)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('moon_beaver_pelt', 'Moon Beaver Pelt', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('fox_pelt_poor', 'Fox Fur (Poor)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('ota_fox_pelt', 'Ota Fox Pelt', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('wolf_pelt_good', 'Wolf Fur (Good)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('katata_elk_pelt', 'Katata Elk Pelt', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('javelina_pelt_good', 'Javelina Skin (Good)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('maza_cougar_pelt', 'Maza Cougar Pelt', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('coyote_pelt_pristine', 'Coyote Fur (Pristine)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('legendary_coyote_pelt', 'Legendary Coyote Fur', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('moonstone_wolf_pelt', 'Moonstone Wolf Pelt', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('goat_pelt_good', 'Goat Hair (Good)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('black_bear_pelt_good', 'Black Bear Fur (Good)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('beaver_pelt_good', 'Beaver Fur (Good)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('pronghorn_pelt_poor', 'Pronghorn Fur (Poor)', 50, 1, 'item_standard', 1);
INSERT INTO `items`(`item`, `label`, `limit`, `can_remove`, `type`, `usable`) VALUES ('boar_pelt_pristine', 'Boar Skin (Pristine)', 50, 1, 'item_standard', 1);