Config = {}

Config.Framework = "vorp" -- "redemrp" or "vorp" or "qbr" or "qbr2" or "redemrp-reboot"

Config.Debug = false
Config.Marker = true
Config.Prompts = {
    Prompt1 = 0x05CA7C52,
    Prompt2 = 0x27D1C284,
    PromptTable = 0x05CA7C52,
}

Config.FixOnesyncIssue_BlockStow = true
Config.SellOnlySkinned = true

Config.Texts = {
    Prompt1 = "Sell Carcass ($)",
    Prompt2 = "Sell Carcass (Provision)",
    BringSome = "Bring some",
    Carcass = "carcass",
    Hunt = "Hunt",
    PromptTable = "Start Butchering",
    Butchering = "Butchering",
    NoCleaver = "You dont have the Butcher Cleaver!",
    NoJob = "You dont have the required job!",
    NoMoney = "You dont have enough money!",
    StayInMarker = "Stay in the marker!",
    CollectedDisplay = "Collected:",
    AnimalCantSell = "You cant sell here this animal!",
    QualityCantSell = "You cant sell here this quality!",
    CantSell = "You can not sell it!",
    JobCantSell = "You dont have the required job!",
    FinishedMission = "You have finished the Butcher Mission!",
    SoldCarcass = "You have sold the carcass!",
    SoldFor = "Carcass sold! Items:",
    SellCarcass = "Sell Carcass",
    ButcherDisplay = "Butcher:",
    ButcherTDisplay = "Butcher Table:",
    MissionDisplay = "Mission:",
    HuntDisplay = "Hunt",
    RewardDisplay = "Reward:",
    ChangeDisplay = "Mission changes at",
    NotPossible = "Sell is not possible!",
}

Config.Textures = {
    cross = {"scoretimer_textures", "scoretimer_generic_cross"},
    locked = {"menu_textures","stamp_locked_rank"},
    tick = {"scoretimer_textures","scoretimer_generic_tick"},
    money = {"inventory_items", "money_moneystack"},
    alert = {"menu_textures", "menu_icon_alert"},
}

Config.MissionReward = {16,25}--MIN AND MAX FOR RANDOM AMOUNT OF $ 
Config.MissionRewardMultiplier = 1.0 -- multiplier for amount of Mission Reward - 1.0 does not change the default one
Config.ButcheringTimer = 10 --seconds

Config.Qualities = {
    --[id] = {"Label", oods},
    [1] = {"Good", 1.0},
    [2] = {"Perfect", 2.0},
    [3] = {"Poor", 0.4},
}

Config.Butchers = {
    [1] = {
        name = "Valentine",
        blip = {enable = true, sprite = -1665418949},
        coords = vector3(-338.678, 765.370, 116.581),
        animals = {`a_c_alligator_03`,`a_c_armadillo_01`,`a_c_badger_01`,}, -- add more animals to array from Config.SellAnimals |  FOR ALL ANIMALS, USE: animals = "all" -- EXAMPLE BUTCHER #2
        quality = {1,2},--buy only quality id 1 or 2 -- Config.Qualities
        extra = 0.1, -- +10% -- IF "tax = -0.1," then it will be -10%
        jobs = false, --For job check. For No Job: "jobs = false," -- EXAMPLE BUTCHER #2
    },
    [2] = {
        name = "Black Market",
        blip = {enable = true, sprite = -1665418949},
        coords = vector3(-1416.581, -2343.007, 42.911),
        animals = "all",--BUYS ALL ANIMAL
        quality = {1,2,3},
        extra = -0.1,
        jobs = false,--NO JOB
    },
    [3] = {
        name = "Tumbleweed",
        blip = {enable = true, sprite = -1665418949},
        coords = vector3(-5507.883, -2948.307, -1.859),
        animals = "all",--BUYS ALL ANIMAL
        quality = {1,2,3},
        extra = 0.1,
        jobs = false,
    },
    [4] = {
        name = "Armadillo",
        blip = {enable = true, sprite = -1665418949},
        coords = vector3(-3691.220, -2621.010, -13.732),
        animals = "all",--BUYS ALL ANIMAL
        quality = {1,2,3},
        extra = 0.1,
        jobs = false,
    },
    [5] = {
        name = "Strawberry",
        blip = {enable = true, sprite = -1665418949},
        coords = vector3(-1753.072, -394.743, 156.186),
        animals = "all",--BUYS ALL ANIMAL
        quality = {1,2,3},
        extra = 0.1,
        jobs = false,
    },
    [6] = {
        name = "North",
        blip = {enable = true, sprite = -1665418949},
        coords = vector3(-1346.974, 2403.894, 307.067),
        animals = "all",--BUYS ALL ANIMAL
        quality = {1,2,3},
        extra = 0.1,
        jobs = false,
    },
    [7] = {
        name = "Wapiti",
        blip = {enable = true, sprite = -1665418949},
        coords = vector3(441.505, 2235.094, 248.113),
        animals = "all",--BUYS ALL ANIMAL
        quality = {1,2,3},
        extra = 0.3,
        jobs = false,
    },
    [8] = {
        name = "Blackwater",
        blip = {enable = true, sprite = -1665418949},
        coords = vector3(-751.089, -1285.019, 43.272),
        animals = "all",--BUYS ALL ANIMAL
        quality = {1,2,3},
        extra = 0.1,
        jobs = false,
    },
    [9] = {
        name = "Rhodes",
        blip = {enable = true, sprite = -1665418949},
        coords = vector3(1296.328, -1279.245, 75.839),
        animals = "all",--BUYS ALL ANIMAL
        quality = {1,2,3},
        extra = 0.1,
        jobs = false,
    },
    [10] = {
        name = "Saint Denis",
        blip = {enable = true, sprite = -1665418949},
        coords = vector3(2816.428, -1326.150, 46.557),
        animals = "all",--BUYS ALL ANIMAL
        quality = {1,2,3},
        extra = 0.1,
        jobs = false,
    },
    [11] = {
        name = "Van Horn",
        blip = {enable = true, sprite = -1665418949},
        coords = vector3(2994.406, 571.607, 44.342),
        animals = "all",--BUYS ALL ANIMAL
        quality = {1,2,3},
        extra = -0.4,
        jobs = false,
    },
    [12] = {
        name = "Annesburg",
        blip = {enable = true, sprite = -1665418949},
        coords = vector3(2932.746, 1302.563, 44.480),
        animals = "all",--BUYS ALL ANIMAL
        quality = {1,2,3},
        extra = -0.1,
        jobs = false,
    },
}

Config.ButcherTables = {
    [1] = {
        name = "Blackwater",
        blip = {enable = true, sprite = 1369919445},
        coords = vector3(-755.526, -1287.967, 43.641),
        heading = 99.407,
        useprice = 2,-- 1 dollar / animal butchering
       jobs = false, --For job check. For No Job: "jobs = false,"
    },
    [2] = {
        name = "Tumbleweed",
        blip = {enable = true, sprite = 1369919445},
        coords = vector3(-5508.219, -2944.834, -1.876),
        heading = 166.478,
        useprice = 1,
       jobs = false,
    },
    [3] = {
        name = "Armadillo",
        blip = {enable = true, sprite = 1369919445},
        coords = vector3(-3695.216, -2630.493, -13.830),
        heading = 85.968,
        useprice = 2,
       jobs = false, 
    },
    [4] = {
        name = "Strawberry",
        blip = {enable = true, sprite = 1369919445},
        coords = vector3(-1752.674, -390.606, 156.276),
        heading = 179.492,
        useprice = 2,
       jobs = false, 
    },
    [5] = {
        name = "North",
        blip = {enable = true, sprite = 1369919445},
        coords = vector3(-1344.678, 2405.222, 307.067),
        heading = 328.470,
        useprice = 4,
       jobs = false, 
    },
    [6] = {
        name = "Wapiti",
        blip = {enable = true, sprite = 1369919445},
        coords = vector3(442.254, 2216.565, 247.455),
        heading = 3.079,
        useprice = 1,
        jobs = {"wapiti", "wapiti"}, 
    },
    [7] = {
        name = "Valentine",
        blip = {enable = true, sprite = 1369919445},
        coords = vector3(-333.814, 764.490, 116.519),
        heading = 1.415,
        useprice = 5,
       jobs = false, 
    },
    [8] = {
        name = "Rhodes",
        blip = {enable = true, sprite = 1369919445},
        coords = vector3(1298.925, -1276.100, 75.906),
        heading = 153.906,
        useprice = 3,
       jobs = false, 
    },
    [9] = {
        name = "Saint Denis",
        blip = {enable = true, sprite = 1369919445},
        coords = vector3(2817.836, -1330.089, 46.514),
        heading = 232.950,
        useprice = 1,
       jobs = false, 
    },
    [10] = {
        name = "Van Horn",
        blip = {enable = true, sprite = 1369919445},
        coords = vector3(2998.530, 567.791, 44.480),
        heading = 199.839,
        useprice = 2,
       jobs = false, 
    },
    [11] = {
        name = "Annesburg",
        blip = {enable = true, sprite = 1369919445},
        coords = vector3(2937.331, 1306.315, 44.479),
        heading = 188.433,
        useprice = 1,
       jobs = false, 
    },
    [12] = {
        name = "Black Market",
        blip = {enable = false, sprite = 1369919445},
        coords = vector3(-1398.425, -2329.781, 43.034),
        heading = 275.857,
        useprice = 10,-- 10 dollar / animal
        jobs = false, --For job check. For No Job: "jobs = false,"
    },
}

Config.SellAnimals = {
    --label = Label of Animal, money = Reward Money for Sell, items = Reward items for Sell, butchering = Reward items for Butchering
    [`a_c_alligator_03`] = {label = "Alligator", money = 15, items = {{"alligator_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "alligator_limb", 1}, { "aligatormeat", 1}, {"fat", 1}}},
    [`a_c_armadillo_01`] = {label = "Armadillo", money = 15, items = {{"armadillo_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "armadillo_limb", 1}, { "stringy", 1}, {"fat", 1}}},
    [`a_c_badger_01`] = {label = "Badger", money = 10, items = {{"badger_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "badger_limb", 1}, { "stringy", 1}, {"fat", 1}}},
    [`a_c_beaver_01`] = {label = "Beaver", money = 10, items = {{"beaver_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "beaver_limb", 1}, { "stringy", 1}, {"fat", 1}}},
    [`a_c_bighornram_01`] = {label = "Big Horn Ram", money = 5, items = {{"ram_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "ram_limb", 1}, { "mutton", 1}, {"fat", 1}}},
    [`a_c_buck_01`] = {label = "Buck", money = 5, items = {{"buck_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "buck_limb", 1}, { "venison", 1}, {"fat", 1}}},
    [`a_c_californiacondor_01`] = {label = "Californian Condor", money = 10, items = {{"ccondor_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "condor_limb", 1}, { "bird", 1}, {"fat", 1}}},
    [`a_c_chicken_01`] = {label = "Chicken", money = 3, items = {{"chicken_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "chicken_limb", 1}, { "bird", 1}, {"fat", 1}}},
    [`a_c_cormorant_01`] = {label = "Cormorant", money = 10, items = {{"cormorant_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "cormorant_limb", 1}, { "bird", 1}, {"fat", 1}}},
    [`a_c_cougar_01`] = {label = "Cougar", money = 10, items = {{"cougar_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "cougar_limb", 1}, { "biggame", 1}, {"fat", 1}}},
    [`a_c_coyote_01`] = {label = "Coyote", money = 5, items = {{"coyote_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "coyote_limb", 1}, { "stringy", 1}, {"fat", 1}}},
    [`a_c_cranewhooping_01`] = {label = "Crane", money = 10, items = {{"crane_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "crane_limb", 1}, { "bird", 1}, {"fat", 1}}},
    [`a_c_deer_01`] = {label = "Deer", money = 5, items = {{"deer_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "deer_limb", 1}, { "venison", 1}, {"fat", 1}}},
    [`a_c_duck_01`] = {label = "Duck", money = 5, items = {{"duck_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "duck_limb", 1}, { "bird", 1}, {"fat", 1}}},
    [`a_c_eagle_01`] = {label = "Eagle", money = 10, items = {{"eagle_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "eagle_limb", 1}, { "bird", 1}, {"fat", 1}}},
    [`a_c_egret_01`] = {label = "Egret", money = 10, items = {{"egret_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "egret_limb", 1}, { "bird", 1}, {"fat", 1}}},
    [`a_c_fishchannelcatfish_01_lg`] = {label = "Catfish", money = 10, items = {{"catfish_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "fish", 1}, {"fat", 1}}},
    [`a_c_fishchannelcatfish_01_xl`] = {label = "Catfish Large", money = 10, items = {{"catfish_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "fish", 1}, {"fat", 1}}},
    [`a_c_fishlakesturgeon_01_lg`] = {label = "Lake Sturgeon", money = 10, items = {{"sturgeon_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "fish", 1}, {"fat", 1}}},
    [`a_c_fishlongnosegar_01_lg`] = {label = "Longnose Gar", money = 10, items = {{"gar_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "fish", 1}, {"fat", 1}}},
    [`a_c_fishmuskie_01_lg`] = {label = "Muskie", money = 10, items = {{"muskie_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "fish", 1}, {"fat", 1}}},
    [`a_c_fishnorthernpike_01_lg`] = {label = "Northern Pike", money = 10, items = {{"pike_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "fish", 1}, {"fat", 1}}},
    [`a_c_fox_01`] = {label = "Fox", money = 10, items = {{"fox_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "fox_limb", 1}, { "stringy", 1}, {"fat", 1}}},
    [`a_c_gilamonster_01`] = {label = "Gila monster", money = 10, items = {{"gila_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "gila_limb", 1}, { "herptile", 1}, {"fat", 1}}},
    [`a_c_goat_01`] = {label = "Goat", money = 5, items = {{"goat_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "goat_limb", 1}, { "mutton", 1}, {"fat", 1}}},
    [`a_c_goosecanada_01`] = {label = "Goose", money = 10, items = {{"goose_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "goose_limb", 1}, { "bird", 1}, {"fat", 1}}},
    [`a_c_hawk_01`] = {label = "Hawk", money = 10, items = {{"hawk_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "hawk_limb", 1}, { "bird", 1}, {"fat", 1}}},
    [`a_c_heron_01`] = {label = "Heron", money = 10, items = {{"heron_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "heron_limb", 1}, { "bird", 1}, {"fat", 1}}},
    [`a_c_iguanadesert_01`] = {label = "Desert Iguana", money = 10, items = {{"diguana_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "iguana_limb", 1}, { "herptile", 1}, {"fat", 1}}},
    [`a_c_iguana_01`] = {label = "Iguana", money = 10, items = {{"iguana_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "iguana_limb", 1}, { "herptile", 1}, {"fat", 1}}},
    [`a_c_javelina_01`] = {label = "Javelina", money = 10, items = {{"javelina_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "javelina_limb", 1}, { "pork", 1}, {"fat", 1}}},
    [`a_c_loon_01`] = {label = "Loon", money = 10, items = {{"loon_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "loon_limb", 1}, { "bird", 1}, {"fat", 1}}},
    [`a_c_muskrat_01`] = {label = "Muskrat", money = 10, items = {{"muskrat_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "muskrat_limb", 1}, { "stringy", 1}, {"fat", 1}}},
    [`a_c_owl_01`] = {label = "Owl", money = 10, items = {{"owl_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "owl_limb", 1}, { "bird", 1}, {"fat", 1}}},
    [`a_c_panther_01`] = {label = "Panther", money = 5, items = {{"panther_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "panther_limb", 1}, { "biggame", 1}, {"fat", 1}}},
    [`a_c_parrot_01`] = {label = "Parrot", money = 10, items = {{"parrot_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "parrot_limb", 1}, { "bird", 1}, {"fat", 1}}},
    [`a_c_pelican_01`] = {label = "Pelican", money = 10, items = {{"pelican_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "pelican_limb", 1}, { "bird", 1}, {"fat", 1}}},
    [`a_c_pheasant_01`] = {label = "Pheasant", money = 10, items = {{"pheasant_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "pheasant_limb", 1}, { "bird", 1}, {"fat", 1}}},
    [`a_c_pig_01`] = {label = "Pig", money = 5, items = {{"pig_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "pig_limb", 1}, { "pork", 1}, {"fat", 1}}},
    [`a_c_possum_01`] = {label = "Opossum", money = 10, items = {{"opossum_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "opossum_limb", 1}, { "stringy", 1}, {"fat", 1}}},
    [`a_c_prairiechicken_01`] = {label = "Prairie Chicken", money = 10, items = {{"pchicken_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "chicken_limb", 1}, { "bird", 1}, {"fat", 1}}},
    [`a_c_pronghorn_01`] = {label = "Pronghorn", money = 10, items = {{"pronghorn_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "pronghorn_limb", 1}, { "venison", 1}, {"fat", 1}}},
    [`a_c_rabbit_01`] = {label = "Rabbit", money = 3, items = {{"rabbit_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "rabbit_limb", 1}, { "game", 1}, {"fat", 1}}},
    [`a_c_raccoon_01`] = {label = "Raccon", money = 5, items = {{"raccoon_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "raccoon_limb", 1}, { "stringy", 1}, {"fat", 1}}},
    [`a_c_raven_01`] = {label = "Raven", money = 5, items = {{"raven_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "raven_limb", 1}, { "bird", 1}, {"fat", 1}}},
    [`a_c_redfootedbooby_01`] = {label = "Red Footed Booby", money = 15, items = {{"booby_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "booby_limb", 1}, { "bird", 1}, {"fat", 1}}},
    [`a_c_rooster_01`] = {label = "Rooster", money = 4, items = {{"rooster_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "rooster_limb", 1}, { "bird", 1}, {"fat", 1}}},
    [`a_c_roseatespoonbill_01`] = {label = "Spoonbill", money = 10, items = {{"spoonbill_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "spoonbill_limb", 1}, { "bird", 1}, {"fat", 1}}},
    [`a_c_seagull_01`] = {label = "Seagull", money = 10, items = {{"seagull_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "seagull_limb", 1}, { "bird", 1}, {"fat", 1}}},
    [`a_c_sheep_01`] = {label = "Sheep", money = 4, items = {{"sheep_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "sheep_limb", 1}, { "mutton", 1}, {"fat", 1}}},
    [`a_c_skunk_01`] = {label = "Skunk", money = 5, items = {{"skunk_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "skunk_limb", 1}, { "stringy", 1}, {"fat", 1}}},
    [`a_c_snakeblacktailrattle_01`] = {label = "Blacktail rattlesnake", money = 10, items = {{"snake_blacktail_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "stringy", 1}, {"fat", 1}}},
    [`a_c_snakeferdelance_01[`] = {label = "Fer de lance snake", money = 10, items = {{"snake_ferdelance_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "stringy", 1}, {"fat", 1}}},
    [`a_c_snakeredboa_01`] = {label = "Boa", money = 10, items = {{"snake_boa_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "stringy", 1}, {"fat", 1}}},
    [`a_c_snakewater_01`] = {label = "Water snake", money = 10, items = {{"snake_water_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "stringy", 1}, {"fat", 1}}},
    [`a_c_snake_01`] = {label = "Snake", money = 10, items = {{"snake_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "stringy", 1}, {"fat", 1}}},
    [`a_c_turkeywild_01`] = {label = "Wild Turkey", money = 3, items = {{"wturkey_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "turkey_limb", 1}, { "bird", 1}, {"fat", 1}}},
    [`a_c_turkey_01`] = {label = "Turkey (1)", money = 3, items = {{"turkey_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "turkey_limb", 1}, { "bird", 1}, {"fat", 1}}},
    [`a_c_turkey_02`] = {label = "Turkey (2)", money = 3, items = {{"turkey_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "turkey_limb", 1}, { "bird", 1}, {"fat", 1}}},
    [`a_c_turtlesnapping_01`] = {label = "Snapping Turtle", money = 10, items = {{"turtle_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "turtle_limb", 1}, { "stringy", 1}, {"fat", 1}}},
    [`a_c_vulture_01`] = {label = "Vulture", money = 10, items = {{"vulture_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "vulture_limb", 1}, { "bird", 1}, {"fat", 1}}},
    [`A_C_Wolf`] = {label = "Wolf (1)", money = 5, items = {{"wolf_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "wolf_limb", 1}, { "biggame", 1}, {"fat", 1}}},
    [`a_c_wolf_medium`] = {label = "Wolf (2)", money = 5, items = {{"wolf_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "wolf_limb", 1}, { "biggame", 1}, {"fat", 1}}},
    [`a_c_wolf_small`] = {label = "Wolf (3)", money = 5, items = {{"wolf_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "wolf_limb", 1}, { "biggame", 1}, {"fat", 1}}},

    [`mp_a_c_beaver_01`] = {label = "Legendary Beaver", money = 10, items = {{"beaver_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "beaver_limb", 1}, { "stringy", 1}, {"fat", 1}}},
    [`mp_a_c_cougar_01`] = {label = "Legendary Cougar", money = 10, items = {{"cougar_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "cougar_limb", 1}, { "biggame", 1}, {"fat", 1}}},
    [`mp_a_c_coyote_01`] = {label = "Legendary Coyote", money = 10, items = {{"coyote_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "coyote_limb", 1}, { "stringy", 1}, {"fat", 1}}},
    [`mp_a_c_panther_01`] = {label = "Legendary Panther", money = 10, items = {{"panther_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "panther_limb", 1}, { "biggame", 1}, {"fat", 1}}},
    [`mp_a_c_wolf_01`] = {label = "Legendary Wolf", money = 10, items = {{"wolf_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "wolf_limb", 1}, { "biggame", 1}, {"fat", 1}}},
    [`mp_a_c_bighornram_01`] = {label = "Legendary Ram", money = 10, items = {{"ram_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "ram_limb", 1}, { "mutton", 1}, {"fat", 1}}},
    [`mp_a_c_buck_01`] = {label = "Legendary Buck", money = 10, items = {{"buck_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "buck_limb", 1}, { "venison", 1}, {"fat", 1}}},
    [`mp_a_c_fox_01`] = {label = "Legendary Fox", money = 10, items = {{"fox_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "fox_limb", 1}, { "stringy", 1}, {"fat", 1}}},
    [`mp_a_c_owl_01`] = {label = "Legendary Owl", money = 10, items = {{"owl_meat", 2}, {"fat", 3}}, butchering = {{"sliced_meat", 1}, { "owl_limb", 1}, { "bird", 1}, {"fat", 1}}},
}


Config.VORPLabels = {
    ["duck_limb"] = "Duck Limb",
    ["beef"] = "Beef",
    ["buck_limb"] = "Buck Limb",
    ["vulture_meat"] = "Vulture Meat",
    ["fishmeat"] = "Bigfish Meat",
    ["spoonbill_meat"] = "Spoonbill Meat",
    ["turtle_limb"] = "Snapping Turtle Limb",
    ["crane_limb"] = "Crane Limb",
    ["ram_meat"] = "Big Horn Ram Meat",
    ["muskie_meat"] = "Muskie Meat",
    ["egret_limb"] = "Egret Limb",
    ["chicken_limb"] = "Chicken Limb",
    ["booby_meat"] = "Red Footed Booby Meat",
    ["butcher_cleaver"] = "Butcher Cleaver",
    ["bird"] = "Bird Meat",
    ["iguana_limb"] = "Iguana Limb",
    ["beaver_limb"] = "Beaver Limb",
    ["armadillo_meat"] = "Armadillo Meat",
    ["hawk_limb"] = "Hawk Limb",
    ["fox_limb"] = "Fox Limb",
    ["badger_limb"] = "Badger Limb",
    ["buck_meat"] = "Buck Meat",
    ["heron_limb"] = "Heron Limb",
    ["rabbit_meat"] = "Rabbit Meat",
    ["alligator_meat"] = "Alligator Meat",
    ["muskrat_limb"] = "Muskrat Limb",
    ["raven_meat"] = "Raven Meat",
    ["javelina_limb"] = "Javelina Limb",
    ["fox_meat"] = "Fox Meat",
    ["sheep_meat"] = "Sheep Meat",
    ["loon_limb"] = "Loon Limb",
    ["herptile"] = "Herptile meat",
    ["goose_limb"] = "Goose Limb",
    ["pelican_meat"] = "Pelican Meat",
    ["cormorant_limb"] = "Cormorant Limb",
    ["pheasant_limb"] = "Pheasant Limb",
    ["raven_limb"] = "Raven Limb",
    ["cougar_limb"] = "Cougar Limb",
    ["condor_limb"] = "Californian Condor Limb",
    ["pheasant_meat"] = "Pheasant Meat",
    ["coyote_limb"] = "Coyote Limb",
    ["diguana_meat"] = "Desert Iguana Meat",
    ["goat_limb"] = "Goat Limb",
    ["goat_meat"] = "Goat Meat",
    ["mutton"] = "Mutton",
    ["seagull_limb"] = "Seagull Limb",
    ["raccoon_limb"] = "Raccon Limb",
    ["hawk_meat"] = "Hawk Meat",
    ["eagle_limb"] = "Eagle Limb",
    ["ram_limb"] = "Big Horn Ram Limb",
    ["booby_limb"] = "Red Footed Booby Limb",
    ["catfish_meat"] = "Catfish Meat",
    ["alligator_limb"] = "Alligator Limb",
    ["aligatormeat"] = "Alligator Meat",
    ["snake_meat"] = "Snake Meat",
    ["skunk_limb"] = "Skunk Limb",
    ["deer_meat"] = "Deer Meat",
    ["chicken_meat"] = "Chicken Meat",
    ["cougar_meat"] = "Cougar Meat",
    ["parrot_meat"] = "Parrot Meat",
    ["panther_meat"] = "Panther Meat",
    ["turkey_limb"] = "Turkey Limb",
    ["muskrat_meat"] = "Muskrat Meat",
    ["panther_limb"] = "Panther Limb",
    ["fat"] = "Animal Fat",
    ["opossum_limb"] = "Opossum Limb",
    ["parrot_limb"] = "Parrot Limb",
    ["venison"] = "Venison",
    ["rooster_limb"] = "Rooster Limb",
    ["gila_limb"] = "Gila monster Limb",
    ["deer_limb"] = "Deer Limb",
    ["vulture_limb"] = "Vulture Limb",
    ["game"] = "Game Meat",
    ["stringy"] = "Stringy meat",
    ["spoonbill_limb"] = "Spoonbill Limb",
    ["pig_limb"] = "Pig Limb",
    ["wolf_limb"] = "Wolf Limb",
    ["pelican_limb"] = "Pelican Limb",
    ["turtle_meat"] = "Snapping Turtle Meat",
    ["opossum_meat"] = "Opossum Meat",
    ["owl_limb"] = "Owl Limb",
    ["goose_meat"] = "Goose Meat",
    ["cormorant_meat"] = "Cormorant Meat",
    ["owl_meat"] = "Owl Meat",
    ["armadillo_limb"] = "Armadillo Limb",
    ["rabbit_limb"] = "Rabbit Limb",
    ["snake_blacktail_meat"] = "Blacktail rattlesnake Meat",
    ["turkey_meat"] = "Turkey Meat",
    ["pig_meat"] = "Pig Meat",
    ["sliced_meat"] = "Sliced Meat",
    ["beaver_meat"] = "Beaver Meat",
    ["snake_boa_meat"] = "Boa Meat",
    ["sheep_limb"] = "Sheep Limb",
    ["heron_meat"] = "Heron Meat",
    ["javelina_meat"] = "Javelina Meat",
    ["snake_water_meat"] = "Water snake Meat",
    ["pike_meat"] = "Northern Pike Meat",
    ["egret_meat"] = "Egret Meat",
    ["pronghorn_meat"] = "Pronghorn Meat",
    ["seagull_meat"] = "Seagull Meat",
    ["skunk_meat"] = "Skunk Meat",
    ["sturgeon_meat"] = "Lake Sturgeon Meat",
    ["pchicken_meat"] = "Prairie Chicken Meat",
    ["coyote_meat"] = "Coyote Meat",
    ["snake_ferdelance_meat"] = "Fer de lance snake Meat",
    ["loon_meat"] = "Loon Meat",
    ["eagle_meat"] = "Eagle Meat",
    ["gila_meat"] = "Gila monster Meat",
    ["iguana_meat"] = "Iguana Meat",
    ["badger_meat"] = "Badger Meat",
    ["crane_meat"] = "Crane Meat",
    ["wolf_meat"] = "Wolf Meat",
    ["gar_meat"] = "Longnose Gar Meat",
    ["rooster_meat"] = "Rooster Meat",
    ["pork"] = "Pork",
    ["raccoon_meat"] = "Raccoon Meat",
    ["biggame"] = "Big Game Meat",
    ["ccondor_meat"] = "Californian Condor Meat",
    ["duck_meat"] = "Duck Meat",
    ["pronghorn_limb"] = "Pronghorn Limb",    
}
--[[
    --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    --REDEM:RP INVENTORY 2.0 ITEM
    --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    -- IMPORTANT ! Make Sure to not Duplicate any item !
    --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    --BASIC MEATS:
    --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    ["biggame"] =
        {
                label = "Big Game Meat",
                description = "Raw meat",
                weight = 0.1,
                canBeDropped = true,
                canBeUsed = true,
                requireLvl = 0,
                limit = 100,
                imgsrc = "items/biggame.png",
                type = "item_standard",
        },
            
    ["venison"] =
        {
                label = "Venison",
                description = "Raw meat",
                weight = 0.1,
                canBeDropped = true,
                canBeUsed = true,
                requireLvl = 0,
                limit = 100,
                imgsrc = "items/venison.png",
                type = "item_standard",
        },
        
    ["beef"] =
        {
                label = "Beef",
                description = "Raw meat",
                weight = 0.1,
                canBeDropped = true,
                canBeUsed = true,
                requireLvl = 0,
                limit = 100,
                imgsrc = "items/beef.png",
                type = "item_standard",
        },

    ["aligatormeat"] =
        {
                label = "Alligator Meat",
                description = "Raw meat",
                weight = 0.1,
                canBeDropped = true,
                canBeUsed = true,
                requireLvl = 0,
                limit = 100,
                imgsrc = "items/biggame.png",
                type = "item_standard",
        },
        
    ["bird"] =
        {
                label = "Bird Meat",
                description = "Raw meat",
                weight = 0.1,
                canBeDropped = true,
                canBeUsed = true,
                requireLvl = 0,
                limit = 100,
                imgsrc = "items/bird.png",
                type = "item_standard",
        },
        
    ["game"] =
        {
                label = "Game Meat",
                description = "Raw meat",
                weight = 0.1,
                canBeDropped = true,
                canBeUsed = true,
                requireLvl = 0,
                limit = 100,
                imgsrc = "items/game.png",
                type = "item_standard",
        },
        
    ["pork"] =
        {
                label = "Pork",
                description = "Raw meat",
                weight = 0.1,
                canBeDropped = true,
                canBeUsed = true,
                requireLvl = 0,
                limit = 100,
                imgsrc = "items/pork.png",
                type = "item_standard",
        },

    ["fishmeat"] =
        {
                label = "Bigfish Meat",
                description = "Raw meat",
                weight = 0.1,
                canBeDropped = true,
                canBeUsed = true,
                requireLvl = 0,
                limit = 100,
                imgsrc = "items/fish.png",
                type = "item_standard",
        },
        
    ["herptile"] =
        {
                label = "Herptile meat",
                description = "Raw meat",
                weight = 0.1,
                canBeDropped = true,
                canBeUsed = true,
                requireLvl = 0,
                limit = 100,
                imgsrc = "items/herptile.png",
                type = "item_standard",
        },
        
    ["stringy"] =
        {
                label = "Stringy meat",
                description = "Raw meat",
                weight = 0.1,
                canBeDropped = true,
                canBeUsed = true,
                requireLvl = 0,
                limit = 100,
                imgsrc = "items/stringy.png",
                type = "item_standard",
        },
        
    ["mutton"] =
        {
                label = "Mutton",
                description = "Raw meat",
                weight = 0.1,
                canBeDropped = true,
                canBeUsed = true,
                requireLvl = 0,
                limit = 100,
                imgsrc = "items/mutton.png",
                type = "item_standard",
    },
    --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    --------BUTCHER ITEMS--------
    --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    ["butcher_cleaver"] ={label = "Butcher Cleaver", description = "Butchering Item", weight = 0.1, canBeDropped = true, canBeUsed = true, requireLvl = 0, limit = 5, imgsrc = "items/cleaver.png", type = "item_standard",},
    --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    ["sliced_meat"] ={label = "Sliced Meat", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/slicedmeat.png", type = "item_standard",},
    ["fat"] ={label = "Animal Fat", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/fat.png", type = "item_standard",},
    --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    ---UNIQUE ANIMAL MEATS
    --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    ["hawk_meat"] ={label = "Hawk Meat", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/meat.png", type = "item_standard",},
    ["iguana_meat"] ={label = "Iguana Meat", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/meat.png", type = "item_standard",},
    ["javelina_meat"] ={label = "Javelina Meat", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/meat.png", type = "item_standard",},
    ["goat_meat"] ={label = "Goat Meat", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/meat.png", type = "item_standard",},
    ["coyote_meat"] ={label = "Coyote Meat", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/meat.png", type = "item_standard",},
    ["sheep_meat"] ={label = "Sheep Meat", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/meat.png", type = "item_standard",},
    ["rabbit_meat"] ={label = "Rabbit Meat", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/meat.png", type = "item_standard",},
    ["skunk_meat"] ={label = "Skunk Meat", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/meat.png", type = "item_standard",},
    ["eagle_meat"] ={label = "Eagle Meat", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/meat.png", type = "item_standard",},
    ["duck_meat"] ={label = "Duck Meat", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/meat.png", type = "item_standard",},
    ["badger_meat"] ={label = "Badger Meat", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/meat.png", type = "item_standard",},
    ["panther_meat"] ={label = "Panther Meat", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/meat.png", type = "item_standard",},
    ["wolf_meat"] ={label = "Wolf Meat", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/meat.png", type = "item_standard",},
    ["pchicken_meat"] ={label = "Prairie Chicken Meat", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/meat.png", type = "item_standard",},
    ["deer_meat"] ={label = "Deer Meat", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/meat.png", type = "item_standard",},
    ["alligator_meat"] ={label = "Alligator Meat", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/meat.png", type = "item_standard",},
    ["ram_meat"] ={label = "Big Horn Ram Meat", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/meat.png", type = "item_standard",},
    ["pike_meat"] ={label = "Northern Pike Meat", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/meat.png", type = "item_standard",},
    ["rooster_meat"] ={label = "Rooster Meat", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/meat.png", type = "item_standard",},
    ["vulture_meat"] ={label = "Vulture Meat", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/meat.png", type = "item_standard",},
    ["catfish_meat"] ={label = "Catfish Meat", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/meat.png", type = "item_standard",},
    ["gar_meat"] ={label = "Longnose Gar Meat", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/meat.png", type = "item_standard",},
    ["gila_meat"] ={label = "Gila monster Meat", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/meat.png", type = "item_standard",},
    ["turtle_meat"] ={label = "Snapping Turtle Meat", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/meat.png", type = "item_standard",},
    ["crane_meat"] ={label = "Crane Meat", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/meat.png", type = "item_standard",},
    ["booby_meat"] ={label = "Red Footed Booby Meat", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/meat.png", type = "item_standard",},
    ["fox_meat"] ={label = "Fox Meat", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/meat.png", type = "item_standard",},
    ["loon_meat"] ={label = "Loon Meat", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/meat.png", type = "item_standard",},
    ["snake_meat"] ={label = "Snake Meat", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/meat.png", type = "item_standard",},
    ["armadillo_meat"] ={label = "Armadillo Meat", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/meat.png", type = "item_standard",},
    ["snake_ferdelance_meat"] ={label = "Fer de lance snake Meat", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/meat.png", type = "item_standard",},
    ["spoonbill_meat"] ={label = "Spoonbill Meat", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/meat.png", type = "item_standard",},
    ["raven_meat"] ={label = "Raven Meat", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/meat.png", type = "item_standard",},
    ["ccondor_meat"] ={label = "Californian Condor Meat", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/meat.png", type = "item_standard",},
    ["egret_meat"] ={label = "Egret Meat", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/meat.png", type = "item_standard",},
    ["cormorant_meat"] ={label = "Cormorant Meat", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/meat.png", type = "item_standard",},
    ["snake_blacktail_meat"] ={label = "Blacktail rattlesnake Meat", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/meat.png", type = "item_standard",},
    ["seagull_meat"] ={label = "Seagull Meat", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/meat.png", type = "item_standard",},
    ["pronghorn_meat"] ={label = "Pronghorn Meat", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/meat.png", type = "item_standard",},
    ["pheasant_meat"] ={label = "Pheasant Meat", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/meat.png", type = "item_standard",},
    ["raccoon_meat"] ={label = "Raccoon Meat", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/meat.png", type = "item_standard",},
    ["diguana_meat"] ={label = "Desert Iguana Meat", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/meat.png", type = "item_standard",},
    ["chicken_meat"] ={label = "Chicken Meat", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/meat.png", type = "item_standard",},
    ["muskrat_meat"] ={label = "Muskrat Meat", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/meat.png", type = "item_standard",},
    ["snake_water_meat"] ={label = "Water snake Meat", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/meat.png", type = "item_standard",},
    ["heron_meat"] ={label = "Heron Meat", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/meat.png", type = "item_standard",},
    ["goose_meat"] ={label = "Goose Meat", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/meat.png", type = "item_standard",},
    ["snake_boa_meat"] ={label = "Boa Meat", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/meat.png", type = "item_standard",},
    ["muskie_meat"] ={label = "Muskie Meat", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/meat.png", type = "item_standard",},
    ["pelican_meat"] ={label = "Pelican Meat", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/meat.png", type = "item_standard",},
    ["opossum_meat"] ={label = "Opossum Meat", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/meat.png", type = "item_standard",},
    ["pig_meat"] ={label = "Pig Meat", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/meat.png", type = "item_standard",},
    ["sturgeon_meat"] ={label = "Lake Sturgeon Meat", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/meat.png", type = "item_standard",},
    ["buck_meat"] ={label = "Buck Meat", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/meat.png", type = "item_standard",},
    ["turkey_meat"] ={label = "Turkey Meat", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/meat.png", type = "item_standard",},
    ["parrot_meat"] ={label = "Parrot Meat", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/meat.png", type = "item_standard",},
    ["cougar_meat"] ={label = "Cougar Meat", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/meat.png", type = "item_standard",},
    ["beaver_meat"] ={label = "Beaver Meat", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/meat.png", type = "item_standard",},
    ["owl_meat"] ={label = "Owl Meat", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/meat.png", type = "item_standard",},
    --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    --ANIMAL LIMBS
    --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    ["duck_limb"] ={label = "Duck Limb", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/limb.png", type = "item_standard",},
    ["buck_limb"] ={label = "Buck Limb", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/limb.png", type = "item_standard",},
    ["turtle_limb"] ={label = "Snapping Turtle Limb", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/limb.png", type = "item_standard",},
    ["sheep_limb"] ={label = "Sheep Limb", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/limb.png", type = "item_standard",},
    ["ram_limb"] ={label = "Big Horn Ram Limb", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/limb.png", type = "item_standard",},
    ["pelican_limb"] ={label = "Pelican Limb", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/limb.png", type = "item_standard",},
    ["wolf_limb"] ={label = "Wolf Limb", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/limb.png", type = "item_standard",},
    ["javelina_limb"] ={label = "Javelina Limb", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/limb.png", type = "item_standard",},
    ["pig_limb"] ={label = "Pig Limb", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/limb.png", type = "item_standard",},
    ["spoonbill_limb"] ={label = "Spoonbill Limb", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/limb.png", type = "item_standard",},
    ["seagull_limb"] ={label = "Seagull Limb", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/limb.png", type = "item_standard",},
    ["beaver_limb"] ={label = "Beaver Limb", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/limb.png", type = "item_standard",},
    ["deer_limb"] ={label = "Deer Limb", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/limb.png", type = "item_standard",},
    ["chicken_limb"] ={label = "Chicken Limb", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/limb.png", type = "item_standard",},
    ["gila_limb"] ={label = "Gila monster Limb", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/limb.png", type = "item_standard",},
    ["rooster_limb"] ={label = "Rooster Limb", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/limb.png", type = "item_standard",},
    ["parrot_limb"] ={label = "Parrot Limb", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/limb.png", type = "item_standard",},
    ["iguana_limb"] ={label = "Iguana Limb", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/limb.png", type = "item_standard",},
    ["egret_limb"] ={label = "Egret Limb", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/limb.png", type = "item_standard",},
    ["opossum_limb"] ={label = "Opossum Limb", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/limb.png", type = "item_standard",},
    ["pronghorn_limb"] ={label = "Pronghorn Limb", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/limb.png", type = "item_standard",},
    ["raccoon_limb"] ={label = "Raccon Limb", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/limb.png", type = "item_standard",},
    ["turkey_limb"] ={label = "Turkey Limb", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/limb.png", type = "item_standard",},
    ["rabbit_limb"] ={label = "Rabbit Limb", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/limb.png", type = "item_standard",},
    ["booby_limb"] ={label = "Red Footed Booby Limb", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/limb.png", type = "item_standard",},
    ["crane_limb"] ={label = "Crane Limb", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/limb.png", type = "item_standard",},
    ["skunk_limb"] ={label = "Skunk Limb", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/limb.png", type = "item_standard",},
    ["condor_limb"] ={label = "Californian Condor Limb", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/limb.png", type = "item_standard",},
    ["owl_limb"] ={label = "Owl Limb", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/limb.png", type = "item_standard",},
    ["eagle_limb"] ={label = "Eagle Limb", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/limb.png", type = "item_standard",},
    ["panther_limb"] ={label = "Panther Limb", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/limb.png", type = "item_standard",},
    ["goat_limb"] ={label = "Goat Limb", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/limb.png", type = "item_standard",},
    ["coyote_limb"] ={label = "Coyote Limb", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/limb.png", type = "item_standard",},
    ["alligator_limb"] ={label = "Alligator Limb", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/limb.png", type = "item_standard",},
    ["cougar_limb"] ={label = "Cougar Limb", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/limb.png", type = "item_standard",},
    ["raven_limb"] ={label = "Raven Limb", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/limb.png", type = "item_standard",},
    ["pheasant_limb"] ={label = "Pheasant Limb", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/limb.png", type = "item_standard",},
    ["cormorant_limb"] ={label = "Cormorant Limb", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/limb.png", type = "item_standard",},
    ["armadillo_limb"] ={label = "Armadillo Limb", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/limb.png", type = "item_standard",},
    ["goose_limb"] ={label = "Goose Limb", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/limb.png", type = "item_standard",},
    ["loon_limb"] ={label = "Loon Limb", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/limb.png", type = "item_standard",},
    ["muskrat_limb"] ={label = "Muskrat Limb", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/limb.png", type = "item_standard",},
    ["heron_limb"] ={label = "Heron Limb", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/limb.png", type = "item_standard",},
    ["badger_limb"] ={label = "Badger Limb", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/limb.png", type = "item_standard",},
    ["fox_limb"] ={label = "Fox Limb", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/limb.png", type = "item_standard",},
    ["hawk_limb"] ={label = "Hawk Limb", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/limb.png", type = "item_standard",},
    ["vulture_limb"] ={label = "Vulture Limb", description = "Provision", weight = 0.05, canBeDropped = true, canBeUsed = false, requireLvl = 0, limit = 50, imgsrc = "items/limb.png", type = "item_standard",},

------------------------------------------ END REDEMRP ITEMS ------------------------------------------



------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------ QBR CORE ITEM-------------------- MAKE SURE NOT DUPLICATE ANY ITEM
    ['butcher_cleaver'] = {['name'] = 'butcher_cleaver', ['label'] = 'Butcher Cleaver', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/cleaver.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Butchering Item'},
    ------------------------------------------RICX SKINNER ITEMS ------------------------------------------
    ['fishmeat'] = {['name'] = 'fishmeat', ['label'] = 'Bigfish Meat', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/fish.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Raw meat'},
    ['mutton'] = {['name'] = 'mutton', ['label'] = 'Mutton', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/mutton.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Raw meat'},
    ['venison'] = {['name'] = 'venison', ['label'] = 'Venison', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/venison.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Raw meat'},
    ['herptile'] = {['name'] = 'herptile', ['label'] = 'Herptile meat', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/herptile.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Raw meat'},
    ['biggame'] = {['name'] = 'biggame', ['label'] = 'Big Game Meat', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/biggame.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Raw meat'},
    ['stringy'] = {['name'] = 'stringy', ['label'] = 'Stringy meat', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/stringy.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Raw meat'},
    ['pork'] = {['name'] = 'pork', ['label'] = 'Pork', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/pork.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Raw meat'},
    ['aligatormeat'] = {['name'] = 'aligatormeat', ['label'] = 'Alligator Meat', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/biggame.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Raw meat'},
    ['game'] = {['name'] = 'game', ['label'] = 'Game Meat', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/game.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Raw meat'},
    ['bird'] = {['name'] = 'bird', ['label'] = 'Bird Meat', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/bird.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Raw meat'},
    ['beef'] = {['name'] = 'beef', ['label'] = 'Beef', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/beef.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Raw meat'},
        ------------------------------------------RICX BUTCHER NEW------------------------------------------
    ['javelina_meat'] = {['name'] = 'javelina_meat', ['label'] = 'Javelina Meat', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/meat.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['buck_limb'] = {['name'] = 'buck_limb', ['label'] = 'Buck Limb', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/limb.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['deer_limb'] = {['name'] = 'deer_limb', ['label'] = 'Deer Limb', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/limb.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['wolf_meat'] = {['name'] = 'wolf_meat', ['label'] = 'Wolf Meat', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/meat.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['rabbit_limb'] = {['name'] = 'rabbit_limb', ['label'] = 'Rabbit Limb', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/limb.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['panther_meat'] = {['name'] = 'panther_meat', ['label'] = 'Panther Meat', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/meat.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['muskie_meat'] = {['name'] = 'muskie_meat', ['label'] = 'Muskie Meat', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/meat.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['fox_meat'] = {['name'] = 'fox_meat', ['label'] = 'Fox Meat', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/meat.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['raven_limb'] = {['name'] = 'raven_limb', ['label'] = 'Raven Limb', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/limb.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['ccondor_meat'] = {['name'] = 'ccondor_meat', ['label'] = 'Californian Condor Meat', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/meat.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['iguana_meat'] = {['name'] = 'iguana_meat', ['label'] = 'Iguana Meat', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/meat.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['pronghorn_limb'] = {['name'] = 'pronghorn_limb', ['label'] = 'Pronghorn Limb', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/limb.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['pig_meat'] = {['name'] = 'pig_meat', ['label'] = 'Pig Meat', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/meat.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['goose_meat'] = {['name'] = 'goose_meat', ['label'] = 'Goose Meat', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/meat.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['rabbit_meat'] = {['name'] = 'rabbit_meat', ['label'] = 'Rabbit Meat', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/meat.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['cougar_limb'] = {['name'] = 'cougar_limb', ['label'] = 'Cougar Limb', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/limb.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['snake_meat'] = {['name'] = 'snake_meat', ['label'] = 'Snake Meat', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/meat.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['pheasant_limb'] = {['name'] = 'pheasant_limb', ['label'] = 'Pheasant Limb', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/limb.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['raven_meat'] = {['name'] = 'raven_meat', ['label'] = 'Raven Meat', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/meat.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},['cormorant_limb'] = {['name'] = 'cormorant_limb', ['label'] = 'Cormorant Limb', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/limb.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['turkey_limb'] = {['name'] = 'turkey_limb', ['label'] = 'Turkey Limb', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/limb.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['alligator_meat'] = {['name'] = 'alligator_meat', ['label'] = 'Alligator Meat', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/meat.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['turtle_meat'] = {['name'] = 'turtle_meat', ['label'] = 'Snapping Turtle Meat', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/meat.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['vulture_meat'] = {['name'] = 'vulture_meat', ['label'] = 'Vulture Meat', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/meat.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['buck_meat'] = {['name'] = 'buck_meat', ['label'] = 'Buck Meat', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/meat.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['snake_blacktail_meat'] = {['name'] = 'snake_blacktail_meat', ['label'] = 'Blacktail rattlesnake Meat', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/meat.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['skunk_meat'] = {['name'] = 'skunk_meat', ['label'] = 'Skunk Meat', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/meat.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['hawk_meat'] = {['name'] = 'hawk_meat', ['label'] = 'Hawk Meat', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/meat.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['ram_limb'] = {['name'] = 'ram_limb', ['label'] = 'Big Horn Ram Limb', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/limb.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['cougar_meat'] = {['name'] = 'cougar_meat', ['label'] = 'Cougar Meat', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/meat.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['spoonbill_limb'] = {['name'] = 'spoonbill_limb', ['label'] = 'Spoonbill Limb', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/limb.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['owl_limb'] = {['name'] = 'owl_limb', ['label'] = 'Owl Limb', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/limb.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['vulture_limb'] = {['name'] = 'vulture_limb', ['label'] = 'Vulture Limb', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/limb.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['sheep_limb'] = {['name'] = 'sheep_limb', ['label'] = 'Sheep Limb', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/limb.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['badger_meat'] = {['name'] = 'badger_meat', ['label'] = 'Badger Meat', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/meat.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['parrot_meat'] = {['name'] = 'parrot_meat', ['label'] = 'Parrot Meat', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/meat.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['snake_boa_meat'] = {['name'] = 'snake_boa_meat', ['label'] = 'Boa Meat', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/meat.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['eagle_meat'] = {['name'] = 'eagle_meat', ['label'] = 'Eagle Meat', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/meat.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['muskrat_limb'] = {['name'] = 'muskrat_limb', ['label'] = 'Muskrat Limb', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/limb.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['booby_meat'] = {['name'] = 'booby_meat', ['label'] = 'Red Footed Booby Meat', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/meat.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['fox_limb'] = {['name'] = 'fox_limb', ['label'] = 'Fox Limb', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/limb.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},['badger_limb'] = {['name'] = 'badger_limb', ['label'] = 'Badger Limb', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/limb.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['seagull_limb'] = {['name'] = 'seagull_limb', ['label'] = 'Seagull Limb', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/limb.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['snake_ferdelance_meat'] = {['name'] = 'snake_ferdelance_meat', ['label'] = 'Fer de lance snake Meat', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/meat.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['heron_limb'] = {['name'] = 'heron_limb', ['label'] = 'Heron Limb', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/limb.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['hawk_limb'] = {['name'] = 'hawk_limb', ['label'] = 'Hawk Limb', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/limb.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['loon_limb'] = {['name'] = 'loon_limb', ['label'] = 'Loon Limb', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/limb.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['catfish_meat'] = {['name'] = 'catfish_meat', ['label'] = 'Catfish Meat', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/meat.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['goose_limb'] = {['name'] = 'goose_limb', ['label'] = 'Goose Limb', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/limb.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['armadillo_limb'] = {['name'] = 'armadillo_limb', ['label'] = 'Armadillo Limb', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/limb.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['alligator_limb'] = {['name'] = 'alligator_limb', ['label'] = 'Alligator Limb', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/limb.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['rooster_meat'] = {['name'] = 'rooster_meat', ['label'] = 'Rooster Meat', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/meat.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['coyote_limb'] = {['name'] = 'coyote_limb', ['label'] = 'Coyote Limb', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/limb.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['iguana_limb'] = {['name'] = 'iguana_limb', ['label'] = 'Iguana Limb', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/limb.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['pike_meat'] = {['name'] = 'pike_meat', ['label'] = 'Northern Pike Meat', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/meat.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['goat_limb'] = {['name'] = 'goat_limb', ['label'] = 'Goat Limb', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/limb.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['eagle_limb'] = {['name'] = 'eagle_limb', ['label'] = 'Eagle Limb', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/limb.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['panther_limb'] = {['name'] = 'panther_limb', ['label'] = 'Panther Limb', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/limb.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['sheep_meat'] = {['name'] = 'sheep_meat', ['label'] = 'Sheep Meat', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/meat.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['gar_meat'] = {['name'] = 'gar_meat', ['label'] = 'Longnose Gar Meat', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/meat.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['pig_limb'] = {['name'] = 'pig_limb', ['label'] = 'Pig Limb', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/limb.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['condor_limb'] = {['name'] = 'condor_limb', ['label'] = 'Californian Condor Limb', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/limb.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['diguana_meat'] = {['name'] = 'diguana_meat', ['label'] = 'Desert Iguana Meat', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/meat.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['muskrat_meat'] = {['name'] = 'muskrat_meat', ['label'] = 'Muskrat Meat', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/meat.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['beaver_limb'] = {['name'] = 'beaver_limb', ['label'] = 'Beaver Limb', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/limb.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['cormorant_meat'] = {['name'] = 'cormorant_meat', ['label'] = 'Cormorant Meat', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/meat.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['coyote_meat'] = {['name'] = 'coyote_meat', ['label'] = 'Coyote Meat', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/meat.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['opossum_meat'] = {['name'] = 'opossum_meat', ['label'] = 'Opossum Meat', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/meat.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['crane_limb'] = {['name'] = 'crane_limb', ['label'] = 'Crane Limb', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/limb.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['booby_limb'] = {['name'] = 'booby_limb', ['label'] = 'Red Footed Booby Limb', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/limb.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['sliced_meat'] = {['name'] = 'sliced_meat', ['label'] = 'Sliced Meat', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/slicedmeat.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['raccoon_limb'] = {['name'] = 'raccoon_limb', ['label'] = 'Raccon Limb', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/limb.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['turtle_limb'] = {['name'] = 'turtle_limb', ['label'] = 'Snapping Turtle Limb', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/limb.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['egret_limb'] = {['name'] = 'egret_limb', ['label'] = 'Egret Limb', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/limb.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['parrot_limb'] = {['name'] = 'parrot_limb', ['label'] = 'Parrot Limb', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/limb.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['rooster_limb'] = {['name'] = 'rooster_limb', ['label'] = 'Rooster Limb', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/limb.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['spoonbill_meat'] = {['name'] = 'spoonbill_meat', ['label'] = 'Spoonbill Meat', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/meat.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['turkey_meat'] = {['name'] = 'turkey_meat', ['label'] = 'Turkey Meat', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/meat.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['egret_meat'] = {['name'] = 'egret_meat', ['label'] = 'Egret Meat', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/meat.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},['ram_meat'] = {['name'] = 'ram_meat', ['label'] = 'Big Horn Ram Meat', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/meat.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['fat'] = {['name'] = 'fat', ['label'] = 'Animal Fat', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/fat.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['gila_limb'] = {['name'] = 'gila_limb', ['label'] = 'Gila monster Limb', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/limb.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['pronghorn_meat'] = {['name'] = 'pronghorn_meat', ['label'] = 'Pronghorn Meat', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/meat.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['goat_meat'] = {['name'] = 'goat_meat', ['label'] = 'Goat Meat', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/meat.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['wolf_limb'] = {['name'] = 'wolf_limb', ['label'] = 'Wolf Limb', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/limb.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['raccoon_meat'] = {['name'] = 'raccoon_meat', ['label'] = 'Raccoon Meat', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/meat.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['javelina_limb'] = {['name'] = 'javelina_limb', ['label'] = 'Javelina Limb', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/limb.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['pelican_limb'] = {['name'] = 'pelican_limb', ['label'] = 'Pelican Limb', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/limb.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['pchicken_meat'] = {['name'] = 'pchicken_meat', ['label'] = 'Prairie Chicken Meat', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/meat.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['opossum_limb'] = {['name'] = 'opossum_limb', ['label'] = 'Opossum Limb', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/limb.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['chicken_meat'] = {['name'] = 'chicken_meat', ['label'] = 'Chicken Meat', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/meat.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['duck_limb'] = {['name'] = 'duck_limb', ['label'] = 'Duck Limb', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/limb.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['armadillo_meat'] = {['name'] = 'armadillo_meat', ['label'] = 'Armadillo Meat', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/meat.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['owl_meat'] = {['name'] = 'owl_meat', ['label'] = 'Owl Meat', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/meat.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['beaver_meat'] = {['name'] = 'beaver_meat', ['label'] = 'Beaver Meat', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/meat.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['sturgeon_meat'] = {['name'] = 'sturgeon_meat', ['label'] = 'Lake Sturgeon Meat', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/meat.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['pelican_meat'] = {['name'] = 'pelican_meat', ['label'] = 'Pelican Meat', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/meat.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['chicken_limb'] = {['name'] = 'chicken_limb', ['label'] = 'Chicken Limb', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/limb.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['snake_water_meat'] = {['name'] = 'snake_water_meat', ['label'] = 'Water snake Meat', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/meat.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['pheasant_meat'] = {['name'] = 'pheasant_meat', ['label'] = 'Pheasant Meat', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/meat.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['heron_meat'] = {['name'] = 'heron_meat', ['label'] = 'Heron Meat', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/meat.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['deer_meat'] = {['name'] = 'deer_meat', ['label'] = 'Deer Meat', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/meat.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['seagull_meat'] = {['name'] = 'seagull_meat', ['label'] = 'Seagull Meat', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/meat.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['crane_meat'] = {['name'] = 'crane_meat', ['label'] = 'Crane Meat', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/meat.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['loon_meat'] = {['name'] = 'loon_meat', ['label'] = 'Loon Meat', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/meat.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['gila_meat'] = {['name'] = 'gila_meat', ['label'] = 'Gila monster Meat', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/meat.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['duck_meat'] = {['name'] = 'duck_meat', ['label'] = 'Duck Meat', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/meat.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ['skunk_limb'] = {['name'] = 'skunk_limb', ['label'] = 'Skunk Limb', ['weight'] = 1, ['type'] = 'item', ['image'] = 'items/limb.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Provision'},
    ]]
