-- Author '🅱🅻🆄🅴🆈🅴🆂#1364' by Sirec Studio -- 
-- REPORT ANY BUGS ON https://discord.gg/9XNBaQSmMd --


Config = {
    
PressKey = 0xE30CD707, -- (R) Key to press when you are near Chair!
SitKey = 0xF84FA74F, -- (MOUSE 2) Key to press to Show the menuapi to choose the anim!
Align = "right",
    
Text = {
["ic_press"] = "Press",        
["ic_sitdown"] = "Sit Down",
["ic_standup"] = "Stand Up",
["ic_desc"] = "Choose the scenario when you sit down!",
["ic_text"] = "Scenarios",
["ic_subtext"] = "Choose the Scene",
["ic_seatchairsmoke"] = "Seat Cigar",
["ic_seatharmonica"] = "Seat Harmonica",
["ic_seatchair"] = "Seat Chair",
["ic_seatbench"] = "Seat Bench",
["ic_seatwhittle"] = "Seat Whittle",
["ic_seatbenchporch"] = "Porch Drinking",
["ic_chairbanjo"] = "Seat Banjo",
["ic_seatconcertina"] = "Seat Concertina",
["ic_seatguitar"] = "Seat Guitar",
["ic_seatfiddle"] = "Seat Fiddle",
["ic_seatknitting"] = "Seat Knitting",
["ic_seatjawharp"] = "Seat Jawharp",
["ic_knifebadass"] = "Knife BadAss",
["ic_mandolin"] = "Seat Mandolin",
["ic_grooming"] = "Grooming Gross",
["ic_porchsmoking"] = "Porch Smoking",
["ic_groomingposh"] = "Grooming Posh",
["ic_seatfan"] = "Seat Fan",
["ic_lobbyseatchair"] = "Seat Chair Lobby",
["ic_campfireseat"] = "Seat CampFire",
["ic_seatporch"] = "Seat Porch",

["ic_pianotext"] = "Piano Scenarios",
["ic_pianosubtext"] = "Choose the Piano Scene",
["ic_pianodesc"] = "Choose how do you wanna play scenario !",
["ic_humanpiano"] = "Human Piano",
["ic_pianoupperclass"] = "Piano Upperclass",
["ic_pianoriverboat"] = "Piano Riverboat",
["ic_pianosketchy"] = "Piano Sketchy",
["ic_abigailpiano"] = "Abigail Piano(Fem)",
        
},
    
PianoChair = { -- What chair is used at piano locations to sing!
    "p_pianochair01x",
    "p_stool06x",
	"p_benchpiano02x",
	"p_stool08x"
	},
    
Props = {
    "P_CHAIRCOMFY04X",
    "P_CHAIR14X",
    "P_SIT_CHAIRWICKER01B",
    "P_SIT_CHAIRWICKER01A",
    "S_CRATESEAT03X",
    "P_CHAIRWICKER01X",
    "P_CHAIRROCKING06X",
    "P_WINDSORCHAIR03X",
    "P_CHAIR13X",
    "P_CHAIR12X",
    "p_bistrochair01x",
    "p_bistrochair02x",
    "P_CHAIRFOLDING02X",
    "P_CHAIR06X",
    "P_CHAIR22X",
    "P_WOODENCHAIR01X",
    "P_DININGCHAIRS01X",
    "P_WINDSORCHAIR02X",
    "P_LOVESEAT01X",
    "P_BENCH06X",
    "P_BENCH17X",
    "P_COUCH05X",
    "P_COUCH08X",
    "P_BENCH_LOG07X",
    "P_WINDSORBENCH01X",
    "P_BENCH15X",
    "p_seatbench01x",
    "p_chairdesk01x",
    "p_chairdesk02x",
    "p_couch02x",
    "p_woodendeskchair01x",
    "p_chair05x",
    "p_chairrusticsav01x",
    "p_chaircomfy11x",
    "p_medwheelchair01x",
    "p_chairdoctor01x",
    "p_ambchair01x",
    "mp005_s_posse_trad_chair01x",
    "p_chairoffice02x",
    "p_chair_barrel04b",
    "p_chairrustic05x",
    "p_chairrocking03x",
    "p_chaircomfy17x",
    "p_chair07x",
    "p_chaircomfy23x",
    "p_chair37x",
    "p_chaircomfy12x",
    "p_chestchair01x",
    "p_chairdining01x",
    "p_chaircomfy09x",
    "p_chairrustic03x",
    "mp005_s_posse_foldingchair_01x",
    "p_theaterchair01b01x",
    "p_chair04x",
    "p_cs_electricchair01x",
    "s_bfchair04x",
    "p_chair_crate15x",
    "p_chaircomfycombo01x",
    "p_rockingchair01x",
    "p_chairwicker03x",
    "p_chaircomfy01x",
    "p_chair20x",
    "p_chairdining03x",
    "p_chairrustic02x",
    "p_chaircomfy07x",
    "s_chair04x",
    "p_chairrocking02x",
    "p_chaircomfy02",
    "p_chair_privatedining01x",
    "p_chairtall01x",
    "p_chair30x",
    "p_chairpokerfancy01x",
    "p_chaircomfy14x",
    "p_privatelounge_chair01x",
    "p_gen_chair07x",
    "p_oldarmchair01x",
    "p_chaircomfy22x",
    "p_chairrocking04x",
    "p_chair15x",
    "p_ambchair02x",
    "p_chairsalon01x",
    "p_chair_10x",
    "p_chairmed01x",
    "p_chair12bx",
    "p_chaircomfy06x",
    "p_chair18x",
    "p_chair02x",
    "p_chaircomfy03x",
    "p_chair21x",
    "p_rockingchair02x",
    "p_armchair01x",
    "p_chair38x",
    "p_chairmed02x",
    "p_chair27x",
    "p_chair23x",
    "s_electricchair01x",
    "p_chair11x",
    "p_chairdining02x",
    "p_rockingchair03x",
    "p_chair31x",
    "p_chair16x",
    "p_chairdeck01x",
    "p_loveseat02x",
    "p_seatsnorpass01_x",
    "p_seatsnorpass02_x",
    "p_bench03x",
    "p_benchbear01x",
    "p_bench_log05x",
    "p_benchch01x",
    "p_bench_log06x",
    "p_bench09x",
    "p_benchnbx02x",
    "p_woodbench02x",
    "p_bench20x",
    "p_bench18x",
    "p_bench_log04x",
    "p_benchironnbx01x",
    "p_couch06x",
    "p_bench_log02x",
    "p_chairwhite01x"    
	}    
}